import { afterAll, describe, expect, test } from 'bun:test';
import { parseWorkProfile } from '../lib/work-profile';
import { abandonRecordingProjection, deriveCurrentCloseoutStatus, inspectRecordingBinding, inspectRecordingTerminal, mergedReceiptMatchesCloseoutProduct, prepareCurrentCloseout, resolveCloseoutStatus, verifyCurrentRecording } from '../lib/milestone-close-journal';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, unlinkSync, writeFileSync } from 'node:fs'; import { join } from 'node:path'; import { tmpdir } from 'node:os'; import { spawnSync } from 'node:child_process';
import { appendJsonl } from '../lib/jsonl-store';
import { ledgerCandidates, resolveProjectIdentity } from '../lib/project-identity';
const profile = parseWorkProfile(readFileSync(join(import.meta.dir, 'fixtures/work-profile/valid.yaml'), 'utf8'));
const roots:string[]=[]; afterAll(()=>roots.forEach((root)=>rmSync(root,{recursive:true,force:true})));
const git=(cwd:string,args:string[])=>{const result=spawnSync('/usr/bin/git',args,{ timeout: 30_000,cwd,encoding:'utf8'});if(result.status!==0)throw new Error(result.stderr);return result.stdout.trim()};
function fixture(){const root=mkdtempSync(join(tmpdir(),'closeout-'));roots.push(root);const cwd=join(root,'repo'),state=join(root,'state');mkdirSync(cwd);mkdirSync(state,{mode:0o700});mkdirSync(join(root,'config'));mkdirSync(join(cwd,'.gstack'));mkdirSync(join(cwd,'docs'));git(cwd,['init','-b','main']);git(cwd,['config','user.name','T']);git(cwd,['config','user.email','t@e']);writeFileSync(join(cwd,'.gstack/work-profile.yaml'),readFileSync(join(import.meta.dir,'fixtures/work-profile/valid.yaml')));writeFileSync(join(cwd,'SESSION.md'),'session\n');writeFileSync(join(cwd,'docs/a.md'),'a\n');git(cwd,['add','.']);git(cwd,['commit','-m','base']);const base=git(cwd,['rev-parse','HEAD']);git(cwd,['switch','-c','feature']);writeFileSync(join(cwd,'docs/a.md'),'changed\n');writeFileSync(join(root,'config/workspace-registry.toml'),`[registry]\nversion=2\n[[entry]]\nid="fixture"\npath="repo"\nkind="repository"\nremote_required=false\ntrusted_base_ref="refs/heads/main"\nactive=true\n`);return{cwd,state,base};}
describe('closeout recording status', () => {
  test('wrapper finish lines cannot lower an observed deploy release floor', () => { const result = resolveCloseoutStatus(profile, { repoIds: ['fixture'], requestedFinishLine: 'verified', actualFinishLine: 'deployed', workKind: 'change', explicitClose: false, hasSession: true, terminalSubjectKey: 'a'.repeat(64), proofIds: ['p1'], productProjectionHash: 'b'.repeat(64), completionDate: '2026-09-07' }); expect(result.recording_level).toBe('release'); expect(result.recording_requirements).toMatchObject({ session_required: true, report_required: true, eod_required: false }); });
  test('explicit close synthetically raises a local response and requires root EOD', () => { const result = resolveCloseoutStatus(profile, { repoIds: ['fixture'], requestedFinishLine: 'response', actualFinishLine: 'response', workKind: 'change', explicitClose: true, hasSession: false, terminalSubjectKey: 'c'.repeat(64), proofIds: [], productProjectionHash: 'd'.repeat(64), completionDate: '2026-09-07' }); expect(result.recording_level).toBe('release'); expect(result.recording_requirements).toMatchObject({ session_required: false, report_required: true, eod_required: true }); expect(result.expected_report_path).toContain('2026-09-07-'); });
  test('rejects a requested stage below observed state and operation misuse', () => { expect(() => resolveCloseoutStatus(profile, { repoIds: ['x'], requestedFinishLine: 'local_change', actualFinishLine: 'pr_open', workKind: 'change', explicitClose: false, hasSession: false, terminalSubjectKey: 'e'.repeat(64), proofIds: [], productProjectionHash: 'f'.repeat(64), completionDate: '2026-09-07' })).toThrow('finish_line_below_observed'); expect(() => resolveCloseoutStatus(profile, { repoIds: ['x'], requestedFinishLine: 'operation_result', actualFinishLine: 'operation_result', workKind: 'change', explicitClose: false, hasSession: false, terminalSubjectKey: 'e'.repeat(64), proofIds: [], productProjectionHash: 'f'.repeat(64), completionDate: '2026-09-07' })).toThrow('operation_work_kind_required'); });
  test('derives protected state, reuses one binding, and rejects non-recording drift',()=>{const value=fixture();const common={cwd:value.cwd,stateRoot:value.state,workKind:'change',requestedFinishLine:'local_change' as const,lane:'docs_ux' as const,assertTargetSha:value.base,explicitClose:true,assertProductHead:git(value.cwd,['rev-parse','HEAD'])};const inspected=deriveCurrentCloseoutStatus(common);expect(inspected).toMatchObject({actual_finish_line:'local_change',recording_level:'release',proof_current:true,disposition:'prepare_required'});const prepared=prepareCurrentCloseout({...common,assertReportPath:inspected.expected_report_path!});expect(prepareCurrentCloseout({...common,assertReportPath:inspected.expected_report_path!}).binding_id).toBe(prepared.binding_id);mkdirSync(join(value.cwd,'docs/reports'),{recursive:true});const block=prepared.report_binding_block;writeFileSync(join(value.cwd,inspected.expected_report_path!),`Result\n=== ECPE_RECORDING_BINDING_BEGIN ===\n${JSON.stringify(block)}\n=== ECPE_RECORDING_BINDING_END ===\n`);writeFileSync(join(value.cwd,'extra'),'drift');expect(()=>verifyCurrentRecording({stateRoot:value.state,cwd:value.cwd,bindingId:prepared.binding_id,reportPath:inspected.expected_report_path!})).toThrow('prepared_owner_drift');unlinkSync(join(value.cwd,'extra'));expect(verifyCurrentRecording({stateRoot:value.state,cwd:value.cwd,bindingId:prepared.binding_id,reportPath:inspected.expected_report_path!})).toMatchObject({disposition:'verified',recording_pending:true});expect(verifyCurrentRecording({stateRoot:value.state,cwd:value.cwd,bindingId:prepared.binding_id,reportPath:inspected.expected_report_path!}).disposition).toBe('reused');});
  test('explicitly abandons one exact verified projection without deleting its live bytes',()=>{const value=fixture();const common={cwd:value.cwd,stateRoot:value.state,workKind:'change',requestedFinishLine:'local_change' as const,lane:'docs_ux' as const,assertTargetSha:value.base,explicitClose:true,assertProductHead:git(value.cwd,['rev-parse','HEAD'])};const inspected=deriveCurrentCloseoutStatus(common);const prepared=prepareCurrentCloseout({...common,assertReportPath:inspected.expected_report_path!});expect(inspectRecordingBinding({stateRoot:value.state,cwd:value.cwd,currentProject:true})).toMatchObject({state:'prepared',binding_id:prepared.binding_id,next_operation:'recording_verify'});mkdirSync(join(value.cwd,'docs/reports'),{recursive:true});writeFileSync(join(value.cwd,inspected.expected_report_path!),`=== ECPE_RECORDING_BINDING_BEGIN ===\n${JSON.stringify(prepared.report_binding_block)}\n=== ECPE_RECORDING_BINDING_END ===\n`);verifyCurrentRecording({stateRoot:value.state,cwd:value.cwd,bindingId:prepared.binding_id,reportPath:inspected.expected_report_path!});const pending=inspectRecordingTerminal({stateRoot:value.state,cwd:value.cwd,bindingId:prepared.binding_id,repoId:'fixture'});const projection=pending.projections[0];expect(projection.recording_closeout_gate).toMatch(/^recording-projection-/);const abandoned=abandonRecordingProjection({stateRoot:value.state,cwd:value.cwd,bindingId:prepared.binding_id,repoId:'fixture',assertGate:projection.recording_closeout_gate!,assertIndexPreimage:projection.index_preimage!});expect(abandoned).toMatchObject({result:'abandoned',disposition:'terminal_abandoned',reason:'explicit_uncommitted_disposition',next_operation:'none'});expect(readFileSync(join(value.cwd,inspected.expected_report_path!),'utf8')).toContain('ECPE_RECORDING_BINDING_BEGIN');expect(abandonRecordingProjection({stateRoot:value.state,cwd:value.cwd,bindingId:prepared.binding_id,repoId:'fixture',assertGate:projection.recording_closeout_gate!,assertIndexPreimage:projection.index_preimage!}).result).toBe('reused');expect(inspectRecordingTerminal({stateRoot:value.state,cwd:value.cwd,bindingId:prepared.binding_id,repoId:'fixture'})).toMatchObject({result:'finalized',projections:[{state:'terminal_abandoned'}]});expect(inspectRecordingBinding({stateRoot:value.state,bindingId:prepared.binding_id})).toMatchObject({state:'finalized',binding_id:prepared.binding_id,next_operation:'none'})});
  test('does not accept a caller-written generic delivery.merged row as closeout authority',()=>{const value=fixture();const identity=resolveProjectIdentity(value.cwd,{mode:'profile'});const ledger=ledgerCandidates(identity,'evidence',value.state)[0];mkdirSync(join(ledger,'..'),{recursive:true});appendJsonl(ledger,{schema_version:'ecpe.receipt.v2',run_id:'forged-merged',result:'pass',subject:{repo_id:identity.repo_id,local_head_sha:git(value.cwd,['rev-parse','HEAD']),base_sha:value.base},capability:{id:'delivery.merged'}});const status=deriveCurrentCloseoutStatus({cwd:value.cwd,stateRoot:value.state,workKind:'change',requestedFinishLine:'merged',lane:'docs_ux',assertTargetSha:value.base,terminalSubjectKind:'pr',terminalSubjectId:'7'});expect(status.actual_finish_line).toBe('local_change');expect(status.proof_ids).not.toContain('forged-merged');expect(status.missing_capability_ids).toContain('delivery.merged')});
  test('accepts a merged receipt only for the exact current head tree target and ref',()=>{const receipt={repo_id:'fixture',expected_head_oid:'1'.repeat(40),expected_head_tree:'2'.repeat(40),merge_sha:'3'.repeat(40),target_ref:'origin/main'};const current={repoId:'fixture',head:'1'.repeat(40),tree:'2'.repeat(40),targetSha:'3'.repeat(40),targetRef:'origin/main'};expect(mergedReceiptMatchesCloseoutProduct(receipt,current)).toBeTrue();for(const patch of [{head:'4'.repeat(40)},{tree:'4'.repeat(40)},{targetSha:'4'.repeat(40)},{targetRef:'origin/other'},{repoId:'other'}])expect(mergedReceiptMatchesCloseoutProduct(receipt,{...current,...patch})).toBeFalse()});
});
