import { afterEach, describe, expect, test } from 'bun:test';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { admitMergedDelivery, findMergedDeliveryByRawIntent, inspectMergedDelivery } from '../lib/merged-delivery';
import { landingIntentIdForDescriptor } from '../lib/landing-safety';

const roots:string[]=[];
afterEach(()=>{for(const root of roots.splice(0))rmSync(root,{recursive:true,force:true})});
const oid=(value:string)=>value.repeat(40);const hash=(value:string)=>value.repeat(64);

function fixture(active=false){
  const stateRoot=mkdtempSync(join(tmpdir(),'merged-delivery-'));roots.push(stateRoot);
  const descriptor={repoId:'github.com/owner/repo',repositoryNodeId:'R_repo',prNumber:7,expectedHeadOid:oid('2'),expectedBaseOid:oid('1'),targetRef:'origin/main',mode:'direct_observed' as const,providerOperationId:'github.com:direct-pr:7'};
  const ship={current:true as const,receipt_run_id:`evidence-${'e'.repeat(32)}`,state_root_id:`state_${'a'.repeat(32)}`,repo_id:descriptor.repoId,pr:7,base_ref:'origin/main',base_sha:oid('1'),remote_pr_head_sha:oid('2'),remote_pr_head_tree:oid('4'),provider_identity:{repository_node_id:'R_repo',repository_name_with_owner:'owner/repo',head_repository_node_id:'R_repo',head_repository_name_with_owner:'owner/repo',head_ref_name:'feature'},profile_hash:hash('b'),manifest_hash:hash('c'),review_run_ids:[],validation_run_ids:[],release_decision:active?{applicable:true as const,mode:'per_pr' as const,version:'1.0.1',title_policy:'version_prefix' as const}:{applicable:false as const,mode:'none' as const,version:null,title_policy:'free' as const},release_write:active?{} as any:null,candidate_profile:null,promotion:null,canary_subject:null};
  const landing={schema:'ecpe.merged-landing-checkpoint.v1' as const,checkpoint_id:hash('d'),binding_sha256:hash('f'),raw_intent_id:landingIntentIdForDescriptor(descriptor),repo_id:descriptor.repoId,repository_node_id:'R_repo',pr_number:7,expected_head_oid:oid('2'),expected_base_oid:oid('1'),target_ref:'origin/main',provider_operation_id:'github.com:direct-pr:7',merge_sha:oid('3'),merge_tree:oid('4'),merge_parents:[oid('1')] as [string],base_parent_verified:true as const,head_tree_verified:true as const};
  const provider={providerState:'MERGED' as const,repositoryNameWithOwner:'owner/repo',repositoryNodeId:'R_repo',headRepositoryNameWithOwner:'owner/repo',headRepositoryNodeId:'R_repo',headRefName:'feature',targetRef:'origin/main',expectedHeadOid:oid('2'),expectedBaseOid:oid('1'),mergeSha:oid('3'),mergeTree:oid('4'),liveTargetOid:oid('3'),baseParentVerified:true as const,headTreeVerified:true as const,liveTargetVerified:true as const};
  const release=active?{schema:'ecpe.merged-release-checkpoint.v1' as const,checkpoint_id:`merged-release-${'1'.repeat(32)}`,raw_intent_id:landing.raw_intent_id,raw_checkpoint_id:landing.checkpoint_id,repository_node_id:'R_repo',pr_number:7,expected_head_oid:oid('2'),expected_base_oid:oid('1'),expected_head_tree:oid('4'),target_ref:'origin/main',merge_sha:oid('3'),merge_tree:oid('4'),live_target_oid:oid('3'),retirement_id:`release-retirement-${'2'.repeat(32)}`,receipt_run_id:ship.receipt_run_id,release_proof_id:`release-land-proof-${'3'.repeat(32)}`,release_proof_binding_sha256:hash('4'),base_parent_verified:true as const,head_tree_verified:true as const,live_target_verified:true as const,reservation_retained:true as const,binding_sha256:hash('5')}:null;
  const input={stateRoot,stateRootId:ship.state_root_id,cwd:'/fixture',descriptor,shipReceiptId:ship.receipt_run_id,headRepositoryNodeId:'R_repo',headRefName:'feature',expectedHeadTree:oid('4'),mergeSha:oid('3')};
  return{stateRoot,input,ship,landing,provider,release};
}

describe('protected merged delivery admission',()=>{
  test('admits inactive release with zero release inspector calls and reuses durable identity',async()=>{const f=fixture(false);let releaseCalls=0;let providerCalls=0;const deps={inspectShip:()=>structuredClone(f.ship),inspectLanding:()=>structuredClone(f.landing),inspectRelease:async()=>{releaseCalls++;throw new Error('release_must_not_run')},snapshotMerged:async()=>{providerCalls++;return structuredClone(f.provider)}};const first=await admitMergedDelivery(f.input,deps);const second=await admitMergedDelivery(f.input,{...deps,snapshotMerged:async()=>{throw new Error('provider_must_not_repeat')}});expect(first).toMatchObject({schema:'ecpe.merged-delivery-receipt.v1',capability_id:'delivery.merged',ship_receipt_id:f.ship.receipt_run_id,merge_sha:oid('3'),release:{drift_status:'not_applicable',checkpoint:null},provider_base_atomicity:'observed_only'});expect(second).toEqual(first);expect([releaseCalls,providerCalls]).toEqual([0,2]);expect(inspectMergedDelivery(f.stateRoot,first.receipt_id)).toEqual(first);expect(findMergedDeliveryByRawIntent(f.stateRoot,f.landing.raw_intent_id)).toEqual(first)});

  test('admits active release only when the exact release checkpoint matches',async()=>{const f=fixture(true);let releaseCalls=0;const receipt=await admitMergedDelivery(f.input,{inspectShip:()=>structuredClone(f.ship),inspectLanding:()=>structuredClone(f.landing),inspectRelease:async()=>{releaseCalls++;return structuredClone(f.release!)},snapshotMerged:async()=>{throw new Error('inactive_provider_must_not_run')}});expect(receipt.release).toMatchObject({drift_status:'verified',checkpoint:{checkpoint_id:f.release!.checkpoint_id,retirement_id:f.release!.retirement_id}});expect(releaseCalls).toBe(1);const other=fixture(true);await expect(admitMergedDelivery(other.input,{inspectShip:()=>structuredClone(other.ship),inspectLanding:()=>structuredClone(other.landing),inspectRelease:async()=>({...structuredClone(other.release!),receipt_run_id:`evidence-${'0'.repeat(32)}`}),snapshotMerged:async()=>structuredClone(other.provider)})).rejects.toThrow('merged_delivery_release_mismatch')});

  test('rejects tampering and conflicting protected receipts',async()=>{const f=fixture(false);const receipt=await admitMergedDelivery(f.input,{inspectShip:()=>structuredClone(f.ship),inspectLanding:()=>structuredClone(f.landing),snapshotMerged:async()=>structuredClone(f.provider)});const file=join(f.stateRoot,'ecpe','merged-delivery',`${receipt.receipt_id}.json`);const row=JSON.parse(readFileSync(file,'utf8'));row.merge_sha=oid('8');writeFileSync(file,JSON.stringify(row),{mode:0o600});expect(()=>inspectMergedDelivery(f.stateRoot,receipt.receipt_id)).toThrow('merged_delivery_receipt_invalid')});
});
