import { afterEach, describe, expect, test } from 'bun:test';
import { mkdtempSync, rmSync, unlinkSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { inspectMilestoneLandingProjection, readMilestoneBlock, startMilestoneBlock, withMilestoneLandingJournal } from '../lib/milestone-block';
import { admitMergedDelivery } from '../lib/merged-delivery';
import { landingIntentIdForDescriptor } from '../lib/landing-safety';

const roots:string[]=[];afterEach(()=>{for(const root of roots.splice(0))rmSync(root,{recursive:true,force:true})});
function setup(){const state=mkdtempSync(join(tmpdir(),'milestone-admission-'));roots.push(state);const stateId=`state_${'1'.repeat(32)}`;const tuple={code_root_id:'code',workspace_root_id:'workspace',state_root_id:stateId};const started=startMilestoneBlock({stateRoot:state,roots:tuple,codeRootHead:'5'.repeat(40),registryHash:'3'.repeat(64),duration:'P30D',participants:['harness-governance','portfolioops','cdo-os'],lanes:['docs_ux','single_repo_code','cross_repo_contract']});const descriptor={repoId:'github.com/acme/code',repositoryNodeId:'R_repo',prNumber:7,expectedHeadOid:'6'.repeat(40),expectedBaseOid:'7'.repeat(40),targetRef:'origin/main',mode:'direct_observed' as const,providerOperationId:'github.com:direct-pr:7'};const raw=landingIntentIdForDescriptor(descriptor);const landing={kind:'ordinary' as const,participant:'portfolioops' as const,repositoryNodeId:'R_repo',prNumber:7,expectedHeadOid:descriptor.expectedHeadOid,expectedBaseOid:descriptor.expectedBaseOid,targetRef:'origin/main',subjectTree:'8'.repeat(40),rawProviderIntentId:raw,shipReceiptId:`evidence-${'a'.repeat(32)}`,lanes:['single_repo_code'] as const};return{state,stateId,started,descriptor,landing}}
async function protect(f:ReturnType<typeof setup>){const ship={current:true as const,receipt_run_id:f.landing.shipReceiptId!,state_root_id:f.stateId,repo_id:f.descriptor.repoId,pr:7,base_ref:f.landing.targetRef,base_sha:f.landing.expectedBaseOid,remote_pr_head_sha:f.landing.expectedHeadOid,remote_pr_head_tree:f.landing.subjectTree,provider_identity:{repository_node_id:'R_repo',repository_name_with_owner:'acme/code',head_repository_node_id:'R_repo',head_repository_name_with_owner:'acme/code',head_ref_name:'feature'},profile_hash:'2'.repeat(64),manifest_hash:'3'.repeat(64),review_run_ids:[],validation_run_ids:[],release_decision:{applicable:false as const,mode:'none' as const,version:null,title_policy:'free' as const},release_write:null,candidate_profile:null,promotion:null,canary_subject:null};const checkpoint={schema:'ecpe.merged-landing-checkpoint.v1' as const,checkpoint_id:'4'.repeat(64),binding_sha256:'5'.repeat(64),raw_intent_id:f.landing.rawProviderIntentId,repo_id:f.descriptor.repoId,repository_node_id:'R_repo',pr_number:7,expected_head_oid:f.landing.expectedHeadOid,expected_base_oid:f.landing.expectedBaseOid,target_ref:f.landing.targetRef,provider_operation_id:f.descriptor.providerOperationId,merge_sha:'b'.repeat(40),merge_tree:f.landing.subjectTree,merge_parents:[f.landing.expectedBaseOid] as [string],base_parent_verified:true as const,head_tree_verified:true as const};const provider={providerState:'MERGED' as const,repositoryNameWithOwner:'acme/code',repositoryNodeId:'R_repo',headRepositoryNameWithOwner:'acme/code',headRepositoryNodeId:'R_repo',headRefName:'feature',targetRef:f.landing.targetRef,expectedHeadOid:f.landing.expectedHeadOid,expectedBaseOid:f.landing.expectedBaseOid,mergeSha:'b'.repeat(40),mergeTree:f.landing.subjectTree,liveTargetOid:'b'.repeat(40),baseParentVerified:true as const,headTreeVerified:true as const,liveTargetVerified:true as const};const receipt=await admitMergedDelivery({stateRoot:f.state,stateRootId:f.stateId,cwd:'/fixture',descriptor:f.descriptor,shipReceiptId:f.landing.shipReceiptId!,headRepositoryNodeId:'R_repo',headRefName:'feature',expectedHeadTree:f.landing.subjectTree,mergeSha:'b'.repeat(40)},{inspectShip:()=>ship,inspectLanding:()=>checkpoint,snapshotMerged:async()=>provider});return{status:'merged' as const,mergeSha:receipt.merge_sha,expectedHeadOid:receipt.expected_head_oid,expectedBaseOid:receipt.expected_base_oid,intentId:receipt.raw_intent_id,baseAtomicity:'verified' as const,providerBaseAtomicity:receipt.provider_base_atomicity,deliveryReceiptId:receipt.receipt_id,deliveryReceiptBindingSha256:receipt.binding_sha256,landingCheckpointId:receipt.landing_checkpoint.checkpoint_id,landingCheckpointBindingSha256:receipt.landing_checkpoint.binding_sha256,releaseDriftStatus:receipt.release.drift_status,shipReceiptId:receipt.ship_receipt_id}}

describe('milestone typed merged admission',()=>{
  test('rejects raw or synthetic success and persists the exact protected receipt binding',async()=>{const f=setup();await expect(withMilestoneLandingJournal({stateRoot:f.state,assertedBlockId:f.started.block.block_id,landing:f.landing},async()=>({status:'merged' as const,mergeSha:'b'.repeat(40),expectedHeadOid:f.landing.expectedHeadOid,expectedBaseOid:f.landing.expectedBaseOid,intentId:f.landing.rawProviderIntentId,baseAtomicity:'verified' as const} as any))).rejects.toThrow('milestone_landing_checkpoint_mismatch');const synthetic={status:'merged' as const,mergeSha:'b'.repeat(40),expectedHeadOid:f.landing.expectedHeadOid,expectedBaseOid:f.landing.expectedBaseOid,intentId:f.landing.rawProviderIntentId,baseAtomicity:'verified' as const,providerBaseAtomicity:'observed_only' as const,deliveryReceiptId:`merged-delivery-${'c'.repeat(32)}`,deliveryReceiptBindingSha256:'d'.repeat(64),landingCheckpointId:'e'.repeat(64),landingCheckpointBindingSha256:'f'.repeat(64),releaseDriftStatus:'not_applicable' as const,shipReceiptId:f.landing.shipReceiptId!};await expect(withMilestoneLandingJournal({stateRoot:f.state,assertedBlockId:f.started.block.block_id,landing:f.landing,reconcileOnly:true},async()=>synthetic)).rejects.toThrow('merged_delivery_receipt_invalid');const admitted=await protect(f);const merged=await withMilestoneLandingJournal({stateRoot:f.state,assertedBlockId:f.started.block.block_id,landing:f.landing,reconcileOnly:true},async()=>admitted);expect(merged).toMatchObject({deliveryReceiptId:admitted.deliveryReceiptId,providerBaseAtomicity:'observed_only'});expect(readMilestoneBlock(f.state,f.started.block.block_id).landings).toMatchObject([{phase:'checkpointed',delivery_receipt_id:admitted.deliveryReceiptId,delivery_receipt_binding_sha256:admitted.deliveryReceiptBindingSha256,landing_checkpoint_id:admitted.landingCheckpointId,landing_checkpoint_binding_sha256:admitted.landingCheckpointBindingSha256,release_drift_status:'not_applicable'}]);const events=inspectMilestoneLandingProjection(f.state,f.started.block.block_id).events;expect(events.at(-1)).toMatchObject({event:'recording.milestone_checkpoint',delivery_receipt_id:admitted.deliveryReceiptId})});

  test('replays only while the protected admitted checkpoint remains readable',async()=>{const f=setup();const admitted=await protect(f);await withMilestoneLandingJournal({stateRoot:f.state,assertedBlockId:f.started.block.block_id,landing:f.landing},async()=>admitted);let calls=0;const replay=await withMilestoneLandingJournal({stateRoot:f.state,assertedBlockId:f.started.block.block_id,landing:f.landing},async()=>{calls++;throw new Error('provider_repeated')});expect(replay).toMatchObject({recovered:true,deliveryReceiptId:admitted.deliveryReceiptId,shipReceiptId:f.landing.shipReceiptId});expect(calls).toBe(0);unlinkSync(join(f.state,'ecpe','merged-delivery',`${admitted.deliveryReceiptId}.json`));expect(()=>readMilestoneBlock(f.state,f.started.block.block_id)).toThrow('milestone_merged_receipt_invalid')});
});
