/**
 * Regression test for the preamble's HAS_ROUTING probe.
 *
 * Every gstack skill's preamble contains a bash block that detects whether the
 * project routes skills via CLAUDE.md / AGENTS.md:
 *
 *   _HAS_ROUTING="no"
 *   for _RF in CLAUDE.md AGENTS.md; do
 *     if [ -f "$_RF" ] && grep -q "## Skill routing" "$_RF" 2>/dev/null; then
 *       _HAS_ROUTING="yes"
 *     fi
 *   done
 *
 * The block is generated by scripts/resolvers/preamble/generate-preamble-bash.ts
 * into every skill's SKILL.md. This test extracts the LIVE block from a
 * generated skill and executes it against the three routing scenarios, so a
 * future edit that breaks AGENTS.md support — or any of the three outcomes —
 * fails here even if it regenerates cleanly.
 */

import { describe, test, expect } from 'bun:test';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { execFileSync } from 'child_process';

const SKILL_DOC = path.join(import.meta.dir, '..', 'review', 'SKILL.md');

/** Extract the `_HAS_ROUTING` block (init line through its closing `done`). */
function extractProbe(skillDoc: string): string {
  const src = fs.readFileSync(skillDoc, 'utf8');
  const start = src.indexOf('_HAS_ROUTING="no"');
  expect(start, 'generated skill must contain the routing probe').toBeGreaterThan(-1);
  const tail = src.slice(start);
  const end = tail.indexOf('\ndone');
  expect(end, 'probe must be a for/done loop').toBeGreaterThan(-1);
  return tail.slice(0, end + '\ndone'.length);
}

/** Run the probe in a fresh temp dir containing the given files; return HAS_ROUTING. */
function runProbe(probe: string, files: Record<string, string>): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'trprobe-'));
  try {
    for (const [name, body] of Object.entries(files)) {
      fs.mkdirSync(path.dirname(path.join(dir, name)), { recursive: true });
      fs.writeFileSync(path.join(dir, name), body);
    }
    const script = `#!/bin/bash\nset -e\ncd "$1"\n${probe}\necho "HAS_ROUTING: $_HAS_ROUTING"\n`;
    const out = execFileSync('bash', ['-c', script, 'bash', dir], { encoding: 'utf8' });
    const m = out.match(/HAS_ROUTING: (yes|no)/);
    expect(m, 'probe must print HAS_ROUTING').toBeTruthy();
    return m![1];
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

const ROUTED = '## Skill routing\n\n- code review → /review\n';
const PLAIN = '# repo\n';

describe('preamble HAS_ROUTING probe', () => {
  const probe = extractProbe(SKILL_DOC);

  test('probe is generated with AGENTS.md support (guards a revert to CLAUDE.md-only)', () => {
    expect(probe).toContain('AGENTS.md');
  });

  test('both CLAUDE.md and AGENTS.md routed → yes', () => {
    expect(runProbe(probe, { 'CLAUDE.md': ROUTED, 'AGENTS.md': ROUTED })).toBe('yes');
  });

  test('AGENTS.md-only routing → yes (non-Claude hosts)', () => {
    expect(runProbe(probe, { 'AGENTS.md': ROUTED })).toBe('yes');
  });

  test('neither file routed → no', () => {
    expect(runProbe(probe, { 'README.md': PLAIN })).toBe('no');
  });
});
