import { afterAll, describe, expect, test } from 'bun:test';
import { decideLanePromotion } from '../lib/lane-promotion';
import { evaluateAndStopMilestoneSafety, startMilestoneBlock } from '../lib/milestone-block';
import { advancePrivatePilotWorkspace, initPrivatePilotWorkspace } from '../lib/private-pilot-workspace';
import { inspectSafetyDowngradeSource, sealSafetyDowngradeSource } from '../lib/safety-downgrade';
import { applyProfileDowngrade, inspectProfileDowngrade } from '../lib/profile-downgrade-writer';
import { parseWorkProfile } from '../lib/work-profile';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path'; import { tmpdir } from 'node:os'; import { spawnSync } from 'node:child_process';
const cleanup:string[]=[];afterAll(()=>cleanup.forEach(root=>rmSync(root,{recursive:true,force:true})));const git=(cwd:string,args:string[])=>{const result=spawnSync('/usr/bin/git',args,{ timeout: 30_000,cwd,encoding:'utf8'});if(result.status!==0)throw new Error(result.stderr);return result.stdout.trim()};

describe('profile safety stop', () => {
  test('a safety failure never produces a promotion decision', () => {
    expect(decideLanePromotion({ from: 'legacy', to: 'shadow', sampleCount: 100, requiredSamples: 1, safetyFailures: 1, efficiencyRegressed: false })).toMatchObject({ decision: 'safety_stop' });
  });
  test('seals the exact failed pilot subject before a future downgrade workspace',()=>{const root=mkdtempSync(join(tmpdir(),'safety-downgrade-'));cleanup.push(root);const repo=join(root,'repo'),state=join(root,'state');mkdirSync(repo);mkdirSync(state,{mode:0o700});git(repo,['init','-b','main']);git(repo,['config','user.name','T']);git(repo,['config','user.email','t@e']);writeFileSync(join(repo,'a'),'a');git(repo,['add','.']);git(repo,['commit','-m','base']);const head=git(repo,['rev-parse','HEAD']);const tuple={code_root_id:'code',workspace_root_id:'workspace',state_root_id:'state'};const started=startMilestoneBlock({stateRoot:state,roots:tuple,codeRootHead:head,registryHash:'a'.repeat(64),duration:'P30D',participants:['harness-governance','portfolioops','cdo-os'],lanes:['docs_ux','single_repo_code','cross_repo_contract']});const key=`${started.block.block_id}\0portfolioops`;initPrivatePilotWorkspace({stateRoot:state,sourceRepository:repo,purpose:'ecpe-v3-pilot',key,subjectSha:head});advancePrivatePilotWorkspace({stateRoot:state,purpose:'ecpe-v3-pilot',key,assertPhase:'seed',assertHead:head,nextPhase:'terminal',nextHead:head});const stopped=evaluateAndStopMilestoneSafety({stateRoot:state,blockId:started.block.block_id,roots:tuple,sources:[{source_id:'github.pr_state.v1',status:'regressed',status_hash:'b'.repeat(64)}],activations:{docs_ux:{activation:'shadow',profile_lineage_hash:'c'.repeat(64)},single_repo_code:{activation:'enforce',profile_lineage_hash:'d'.repeat(64)},cross_repo_contract:{activation:'legacy',profile_lineage_hash:'e'.repeat(64)}}});const latch=stopped.latch_ids[0];const sealed=sealSafetyDowngradeSource({stateRoot:state,blockId:started.block.block_id,participant:'portfolioops',lane:'single_repo_code',latchId:latch});expect(sealed).toMatchObject({result:'sealed',latch_id:latch,subject_head:head,profile_hash:'d'.repeat(64)});expect(sealSafetyDowngradeSource({stateRoot:state,blockId:started.block.block_id,participant:'portfolioops',lane:'single_repo_code',latchId:latch}).seal_id).toBe(sealed.seal_id);expect(inspectSafetyDowngradeSource({stateRoot:state,participant:'portfolioops',lane:'single_repo_code',latchId:latch}).seal_id).toBe(sealed.seal_id)});

  test('writes one exact downgrade scalar only inside the sealed private workspace', () => {
    const root=mkdtempSync(join(tmpdir(),'safety-downgrade-writer-'));cleanup.push(root);const repo=join(root,'repo'),state=join(root,'state');mkdirSync(repo);mkdirSync(state,{mode:0o700});mkdirSync(join(repo,'.gstack'));
    const profileText=readFileSync(join(import.meta.dir,'fixtures/work-profile/shadow.yaml'),'utf8').replace('activation: shadow','activation: enforce');writeFileSync(join(repo,'.gstack/work-profile.yaml'),profileText);writeFileSync(join(repo,'a'),'a');
    git(repo,['init','-b','main']);git(repo,['config','user.name','T']);git(repo,['config','user.email','t@e']);git(repo,['add','.']);git(repo,['commit','-m','base']);const head=git(repo,['rev-parse','HEAD']);const profileHash=parseWorkProfile(profileText).semantic_policy_hash;
    const tuple={code_root_id:'code',workspace_root_id:'workspace',state_root_id:'state'};const started=startMilestoneBlock({stateRoot:state,roots:tuple,codeRootHead:head,registryHash:'a'.repeat(64),duration:'P30D',participants:['harness-governance','portfolioops','cdo-os'],lanes:['docs_ux','single_repo_code','cross_repo_contract']});const pilotKey=`${started.block.block_id}\0portfolioops`;initPrivatePilotWorkspace({stateRoot:state,sourceRepository:repo,purpose:'ecpe-v3-pilot',key:pilotKey,subjectSha:head});advancePrivatePilotWorkspace({stateRoot:state,purpose:'ecpe-v3-pilot',key:pilotKey,assertPhase:'seed',assertHead:head,nextPhase:'terminal',nextHead:head});
    const stopped=evaluateAndStopMilestoneSafety({stateRoot:state,blockId:started.block.block_id,roots:tuple,sources:[{source_id:'github.pr_state.v1',status:'regressed',status_hash:'b'.repeat(64)}],activations:{docs_ux:{activation:'legacy',profile_lineage_hash:'c'.repeat(64)},single_repo_code:{activation:'enforce',profile_lineage_hash:profileHash},cross_repo_contract:{activation:'legacy',profile_lineage_hash:'e'.repeat(64)}}});const latchId=stopped.latch_ids[0];const seal=sealSafetyDowngradeSource({stateRoot:state,blockId:started.block.block_id,participant:'portfolioops',lane:'single_repo_code',latchId});
    const downgradeKey=`portfolioops\0single_repo_code\0${latchId}`;const workspace=initPrivatePilotWorkspace({stateRoot:state,sourceRepository:repo,purpose:'safety-downgrade',key:downgradeKey,subjectSha:head});expect(seal.seal_id).toMatch(/^seal-/);
    const written=applyProfileDowngrade({stateRoot:state,latchId,lane:'single_repo_code',workspaceHandle:workspace.handle,assertSelector:'/lanes/single_repo_code/activation',target:'shadow'});expect(written).toMatchObject({result:'written',phase:'written',target:'shadow',workspace_handle:workspace.handle});expect(readFileSync(join(repo,'.gstack/work-profile.yaml'),'utf8')).toBe(profileText);expect(readFileSync(join(workspace.checkout_root,'.gstack/work-profile.yaml'),'utf8').replace('activation: shadow','activation: enforce')).toBe(profileText);
    expect(applyProfileDowngrade({stateRoot:state,latchId,lane:'single_repo_code',workspaceHandle:workspace.handle,assertSelector:'/lanes/single_repo_code/activation',target:'shadow'}).result).toBe('reused');expect(inspectProfileDowngrade({stateRoot:state,latchId,lane:'single_repo_code'})).toMatchObject({result:'written',record_id:written.record_id,workspace_handle:workspace.handle});expect(()=>applyProfileDowngrade({stateRoot:state,latchId,lane:'single_repo_code',workspaceHandle:workspace.handle,assertSelector:'/lanes/single_repo_code/activation',target:'legacy'})).toThrow('downgrade_intent_conflict');
  });
});
