#!/usr/bin/env bash
if [ -x /c/Users/Mohab/.bun/bin/bun.exe ]; then
  exec /c/Users/Mohab/.bun/bin/bun.exe "$@"
elif [ -x /c/Users/Mohab/.bun/bin/bun ]; then
  exec /c/Users/Mohab/.bun/bin/bun "$@"
elif [ -x /mnt/c/Users/Mohab/.bun/bin/bun.exe ]; then
  exec /mnt/c/Users/Mohab/.bun/bin/bun.exe "$@"
elif [ -x /mnt/c/Users/Mohab/.bun/bin/bun ]; then
  exec /mnt/c/Users/Mohab/.bun/bin/bun "$@"
elif [ -x "$HOME/.bun/bin/bun" ]; then
  exec "$HOME/.bun/bin/bun" "$@"
elif [ -x /bin/bun ]; then
  exec /bin/bun "$@"
else
  exec bun "$@"
fi
