/**
 * Fixture -> SQL seed generator.
 *
 * Emits the demo dataset as portable INSERT statements so it can be loaded into
 * any Postgres that has the migrations applied — a local cluster, a Supabase
 * project, a CI database. It is a development convenience, not a production
 * path: every row it writes carries `data_status = 'demo'`, and `getServerEnv()`
 * refuses the fixture adapter under `NODE_ENV=production`, so loading this into
 * a production database would put demo rows behind an adapter that is allowed
 * to serve them as real. Do not.
 *
 * Properties with no image of their own get the generated illustration from
 * `scripts/generate-property-art.ts`. That is a drawing, not a photograph, and
 * says so inside the image itself — these properties are invented, and a stock
 * photo of a real building attached to one would be a fabricated fact with a
 * picture frame around it.
 *
 *   npx vite-node scripts/generate-seed.ts > seed.sql
 *   psql -d propiq -f seed.sql
 */

import { DEMO_LOCALITIES, BENGALURU } from '../src/data/fixtures/localities';
import { DEMO_DEVELOPERS, DEMO_PROJECTS, DEMO_PROPERTIES } from '../src/data/fixtures/properties';

/** Single-quote escaping. Every value here is ours, but SQL generation that
 *  interpolates without escaping is a habit worth never forming. */
const q = (v: string | undefined | null): string =>
  v === undefined || v === null ? 'null' : `'${v.replace(/'/g, "''")}'`;

const n = (v: number | undefined | null): string =>
  v === undefined || v === null || Number.isNaN(v) ? 'null' : String(v);

const b = (v: boolean | undefined): string => (v === undefined ? 'null' : v ? 'true' : 'false');

const arr = (v: readonly string[]): string =>
  v.length === 0 ? "'{}'" : `array[${v.map(q).join(', ')}]::text[]`;

const json = (v: unknown): string => (v === undefined ? 'null' : q(JSON.stringify(v)));

/**
 * Some tables require `data_status` where the domain type carries none —
 * `Developer` and `Project` describe the company and the scheme, not a measured
 * fact. Every row this script writes comes out of the demo fixture module, so
 * the literal is the accurate value rather than an assumption: there is no
 * other status a row from this file could truthfully have.
 */
const DEMO = `'demo'`;

const out: string[] = [];
const w = (s: string) => out.push(s);

w('-- PropIQ demo dataset. Generated by scripts/generate-seed.ts — do not edit.');
w('-- Every row is dataStatus=demo. Never load into a production database.');
w('begin;');
w('');

w(`insert into cities (id, name, slug, state, lat, lng, coverage)`);
w(`values (${q(BENGALURU)}, 'Bengaluru', 'bengaluru', 'Karnataka', 12.9716, 77.5946, 'live')`);
w(`on conflict (id) do nothing;`);
w('');

// Micro-markets are a foreign key on localities but have no fixture module of
// their own; they are derived from the ids the localities already reference.
const microMarkets = new Map<string, string>();
for (const l of DEMO_LOCALITIES) {
  if (l.microMarketId && !microMarkets.has(l.microMarketId)) {
    microMarkets.set(l.microMarketId, l.name);
  }
}
// Projects can sit in a micro-market no locality names, so both sides feed the
// set or the foreign key fails on the project insert.
for (const p of DEMO_PROJECTS) {
  if (p.microMarketId && !microMarkets.has(p.microMarketId)) {
    const derived = p.microMarketId.replace(/^mm-/, '').replace(/(^|-)(\w)/g, (_m, sep, c) =>
      (sep ? ' ' : '') + c.toUpperCase(),
    );
    microMarkets.set(p.microMarketId, derived);
  }
}
for (const [id, name] of microMarkets) {
  const slug = id.replace(/^mm-/, '');
  w(`insert into micro_markets (id, city_id, name, slug)`);
  w(`values (${q(id)}, ${q(BENGALURU)}, ${q(name)}, ${q(slug)})`);
  w(`on conflict (id) do nothing;`);
}
w('');

for (const l of DEMO_LOCALITIES) {
  w(
    `insert into localities (id, city_id, micro_market_id, name, slug, summary, lat, lng, current_median_price_per_sqft, gross_rental_yield_percent, active_supply_units, annual_absorption_units, nearest_metro_station, metro_distance_km, metro_eta_months, arterial_road_distance_km, airport_distance_km, schools_within_3km, hospitals_within_5km, malls_within_5km, parks_within_2km, pm25_annual, flood_risk, water_stress, average_peak_traffic_index, employment, rent_history, data_status)`,
  );
  w(
    `values (${q(l.id)}, ${q(l.cityId)}, ${q(l.microMarketId)}, ${q(l.name)}, ${q(l.slug)}, ${q(l.summary)}, ${n(l.center.lat)}, ${n(l.center.lng)}, ${n(l.currentMedianPricePerSqFt)}, ${n(l.grossRentalYieldPercent)}, ${n(l.activeSupplyUnits)}, ${n(l.annualAbsorptionUnits)}, ${q(l.transit?.nearestMetroStation)}, ${n(l.transit?.metroDistanceKm)}, ${n(l.transit?.metroEtaMonths)}, ${n(l.transit?.arterialRoadDistanceKm)}, ${n(l.transit?.airportDistanceKm)}, ${n(l.social?.schoolsWithin3Km)}, ${n(l.social?.hospitalsWithin5Km)}, ${n(l.social?.mallsWithin5Km)}, ${n(l.social?.parksWithin2Km)}, ${n(l.environment?.pm25Annual)}, ${n(l.environment?.floodRisk)}, ${n(l.environment?.waterStress)}, ${n(l.environment?.averagePeakTrafficIndex)}, ${json(l.employment)}, ${json(l.rentHistory)}, ${q(l.dataStatus)})`,
  );
  w(`on conflict (id) do nothing;`);
}
w('');

for (const d of DEMO_DEVELOPERS) {
  w(
    `insert into developers (id, name, slug, incorporated_year, headquarters, projects_delivered, units_delivered, average_delay_months, ongoing_litigation_count, rera_complaints_count, data_status)`,
  );
  w(
    `values (${q(d.id)}, ${q(d.name)}, ${q(d.slug)}, ${n(d.incorporatedYear)}, ${q(d.headquarters)}, ${n(d.projectsDelivered)}, ${n(d.unitsDelivered)}, ${n(d.averageDelayMonths)}, ${n(d.ongoingLitigationCount)}, ${n(d.reraComplaintsCount)}, ${DEMO})`,
  );
  w(`on conflict (id) do nothing;`);
}
w('');

for (const p of DEMO_PROJECTS) {
  w(
    `insert into projects (id, name, slug, developer_id, locality_id, micro_market_id, city_id, lat, lng, total_units, land_area_acres, open_space_percent, amenities, data_status)`,
  );
  w(
    `values (${q(p.id)}, ${q(p.name)}, ${q(p.slug)}, ${q(p.developerId)}, ${q(p.localityId)}, ${q(p.microMarketId)}, ${q(p.cityId)}, ${n(p.location.lat)}, ${n(p.location.lng)}, ${n(p.totalUnits)}, ${n(p.landAreaAcres)}, ${n(p.openSpacePercent)}, ${arr(p.amenities ?? [])}, ${DEMO})`,
  );
  w(`on conflict (id) do nothing;`);
}
w('');

// A unit type is the floor plan a property is an instance of. The fixture
// properties reference one each but carry it inline rather than as a separate
// module, so it is reconstructed from the property's own measurements.
for (const p of DEMO_PROPERTIES) {
  if (!p.unitTypeId) continue;
  w(`insert into unit_types (id, project_id, label, bedrooms, carpet_area_sqft, super_built_up_area_sqft)`);
  w(
    `values (${q(p.unitTypeId)}, ${q(p.projectId)}, ${q(`${p.bedrooms} BHK`)}, ${n(p.bedrooms)}, ${n(p.carpetAreaSqFt ?? p.areaSqFt)}, ${n(p.areaSqFt)})`,
  );
  w(`on conflict (id) do nothing;`);
}
w('');

for (const p of DEMO_PROPERTIES) {
  w(
    `insert into properties (id, unit_type_id, project_id, title, kind, construction_status, bedrooms, bathrooms, area_sqft, area_basis, carpet_area_sqft, floor, total_floors, facing, asking_price, pricing, maintenance_per_sqft_month, expected_rent_per_month, locality_id, city_id, lat, lng, listed_at, images, data_status, commercial_developer_relationship, commercial_paid_placement, commercial_commission_possible, commercial_note)`,
  );
  w(
    `values (${q(p.id)}, ${q(p.unitTypeId)}, ${q(p.projectId)}, ${q(p.title)}, ${q(p.kind)}, ${q(p.constructionStatus)}, ${n(p.bedrooms)}, ${n(p.bathrooms)}, ${n(p.areaSqFt)}, ${q(p.areaBasis)}, ${n(p.carpetAreaSqFt)}, ${n(p.floor)}, ${n(p.totalFloors)}, ${q(p.facing)}, ${n(p.askingPrice)}, ${json(p.pricing)}, ${n(p.maintenancePerSqFtMonth)}, ${n(p.expectedRentPerMonth)}, ${q(p.localityId)}, ${q(p.cityId)}, ${n(p.location.lat)}, ${n(p.location.lng)}, ${q(p.listedAt)}, ${arr(p.images.length > 0 ? p.images : [`/property-art/${p.id}.svg`])}, ${q(p.dataStatus)}, ${b(p.commercial.developerRelationship)}, ${b(p.commercial.paidPlacement)}, ${b(p.commercial.commissionPossible)}, ${q(p.commercial.note)})`,
  );
  w(`on conflict (id) do nothing;`);
}
w('');
w('commit;');
w(
  `-- ${DEMO_LOCALITIES.length} localities, ${DEMO_DEVELOPERS.length} developers, ${DEMO_PROJECTS.length} projects, ${DEMO_PROPERTIES.length} properties.`,
);

process.stdout.write(out.join('\n') + '\n');
