import * as fs from 'node:fs';import * as path from 'node:path';import { durableAtomicWrite } from './durable-atomic-write';
type Activation = 'legacy' | 'shadow' | 'enforce';export type PromotionLane='docs_ux'|'single_repo_code'|'cross_repo_contract';type Lane=PromotionLane;const RANK = { legacy: 0, shadow: 1, enforce: 2 } as const;
export const LANE_PROMOTION_POLICY=Object.freeze({policy_id:'ecpe-v3-portfolioops-pilot-v1',purpose:'ecpe-v3-pilot',participant:'portfolioops',lanes:{docs_ux:{terminal_comparisons:3,distinct_heads:2,elapsed_days:7},single_repo_code:{terminal_comparisons:5,distinct_heads:3,elapsed_days:14},cross_repo_contract:{terminal_comparisons:3,distinct_heads:2,elapsed_days:14}},active_canary:{minimum_distinct_heads:3,maximum_distinct_heads:5}} as const);
const canonical=(value:unknown):string=>{if(Array.isArray(value))return`[${value.map(canonical).join(',')}]`;if(value&&typeof value==='object'){const row=value as Record<string,unknown>;return`{${Object.keys(row).sort().map(key=>`${JSON.stringify(key)}:${canonical(row[key])}`).join(',')}}`;}return JSON.stringify(value)};
const digest=(value:unknown)=>new Bun.CryptoHasher('sha256').update(canonical(value)).digest('hex');
export const LANE_PROMOTION_POLICY_HASH=digest(LANE_PROMOTION_POLICY);
export interface LanePromotionSnapshot{block_id:string;participant:'portfolioops';lane:Lane;activation:Activation;profile_hash:string;subject_head:string;subject_tree:string;terminal_comparison_ids:string[];distinct_subject_heads:string[];elapsed_days:number;surface_coverage_complete:boolean;hard_floor_coverage_complete:boolean;safety_statuses:Array<'pass'|'not_applicable'|'unknown'|'regressed'>;unauthorized_effects:number;content_leak_events:number;added_paid_or_helper_calls:number;unknown_validator_baselines:number;efficiency_regressed:boolean}
export function assessLanePromotionSnapshot(input:LanePromotionSnapshot){if(input.activation!=='shadow')throw new Error('promotion_activation_invalid');if(!/^[0-9a-f]{64}$/.test(input.profile_hash)||!(/^[0-9a-f]{40}$/.test(input.subject_head)&&/^[0-9a-f]{40}$/.test(input.subject_tree)))throw new Error('promotion_subject_invalid');const threshold=LANE_PROMOTION_POLICY.lanes[input.lane];const reasons:string[]=[];if(input.safety_statuses.includes('regressed')||input.unauthorized_effects>0||input.content_leak_events>0)reasons.push('safety_regressed');if(input.safety_statuses.includes('unknown'))reasons.push('safety_unknown');if(input.terminal_comparison_ids.length<threshold.terminal_comparisons)reasons.push('insufficient_comparisons');if(new Set(input.distinct_subject_heads).size<threshold.distinct_heads)reasons.push('insufficient_distinct_heads');if(input.elapsed_days<threshold.elapsed_days)reasons.push('insufficient_duration');if(!input.surface_coverage_complete)reasons.push('surface_coverage_incomplete');if(!input.hard_floor_coverage_complete)reasons.push('hard_floor_coverage_incomplete');if(input.added_paid_or_helper_calls>0)reasons.push('added_paid_or_helper_call');if(input.unknown_validator_baselines>0)reasons.push('unknown_validator_baseline');if(input.efficiency_regressed)reasons.push('efficiency_regressed');const unique=[...new Set(reasons)].sort();const eligible=unique.length===0;const body={schema:'ecpe.lane-promotion-eligibility.v1' as const,policy_id:LANE_PROMOTION_POLICY.policy_id,policy_hash:LANE_PROMOTION_POLICY_HASH,block_id:input.block_id,participant:input.participant,lane:input.lane,profile_hash:input.profile_hash,subject_head:input.subject_head,subject_tree:input.subject_tree,terminal_comparison_ids:[...input.terminal_comparison_ids].sort(),eligible,reason_codes:unique};return{...body,proof_id:eligible?`promotion-${digest(body).slice(0,32)}`:null}}
function assessmentFile(stateRoot:string,blockId:string,lane:Lane):string{if(!/^block-[0-9a-f]{32}$/.test(blockId)||!Object.hasOwn(LANE_PROMOTION_POLICY.lanes,lane))throw new Error('promotion_subject_invalid');return path.join(path.resolve(stateRoot),'ecpe','lane-promotions',`${blockId}-${lane}.json`)}
function write(target:string,value:unknown){durableAtomicWrite(target,canonical(value)+'\n')}
export function recordLanePromotionAssessment(input:{stateRoot:string;snapshot:LanePromotionSnapshot}){const result=assessLanePromotionSnapshot(input.snapshot);const payload={schema:'ecpe.lane-promotion-assessment-store.v1',snapshot_hash:digest(input.snapshot),assessment:result};const target=assessmentFile(input.stateRoot,input.snapshot.block_id,input.snapshot.lane);if(fs.existsSync(target)){const existing=JSON.parse(fs.readFileSync(target,'utf8'));if(existing.schema!=='ecpe.lane-promotion-assessment-store.v1')throw new Error('promotion_assessment_invalid');if(existing.snapshot_hash===payload.snapshot_hash&&canonical(existing.assessment)===canonical(result))return{result:'reused',...existing.assessment};if(existing.assessment?.eligible)throw new Error('promotion_evidence_moved')}write(target,payload);return{result:result.eligible?'eligible':'ineligible',...result}}
export function inspectLanePromotionAssessment(input:{stateRoot:string;blockId:string;participant:'portfolioops';lane:Lane}){let value:any;try{value=JSON.parse(fs.readFileSync(assessmentFile(input.stateRoot,input.blockId,input.lane),'utf8'))}catch{throw new Error('promotion_assessment_missing')}if(value.schema!=='ecpe.lane-promotion-assessment-store.v1'||value.assessment?.block_id!==input.blockId||value.assessment?.participant!==input.participant||value.assessment?.lane!==input.lane||value.assessment?.policy_hash!==LANE_PROMOTION_POLICY_HASH)throw new Error('promotion_assessment_invalid');return{result:value.assessment.eligible?'eligible':'ineligible',phase:value.assessment.eligible?'eligible':'collecting',...value.assessment,next_operation:value.assessment.eligible?'apply_profile_promotion':'lane_promotion_check'}}
export function decideLanePromotion(input: { from: Activation; to: Activation; sampleCount: number; requiredSamples: number; safetyFailures: number; efficiencyRegressed: boolean }) { if (RANK[input.to] !== RANK[input.from] + 1) throw new Error('promotion_not_monotonic'); if (!Number.isSafeInteger(input.sampleCount) || !Number.isSafeInteger(input.requiredSamples) || input.requiredSamples <= 0) throw new Error('promotion_sample_invalid'); const decision = input.safetyFailures > 0 ? 'safety_stop' : input.sampleCount < input.requiredSamples ? 'collect_more' : input.efficiencyRegressed ? 'efficiency_regressed' : 'promote'; const body = { ...input, decision }; return { ...body, decision_id: `promotion-${digest(body).slice(0, 24)}` }; }
