import * as fs from 'node:fs';
import * as path from 'node:path';
import { spawnSync } from 'node:child_process';
import { buildChangeManifest } from './change-manifest';
import { ledgerCandidates, readJsonlUnion, resolveProjectIdentity } from './project-identity';
import { resolveProfileValidatorBinding } from './profile-validator-binding';
import { resolveTrustedWorkProfile } from './trusted-base';
import { evaluateValidatorBinding } from './validator-runner';
import { resolveProfileRequirements, type FinishLine, type Lane, type ParsedWorkProfile } from './work-profile';
import { hasHarnessVerificationCleanupAck, milestoneBlockReportKey, readMilestoneBlock, updateMilestoneBlock, type DurableMilestoneLanding, type MilestoneRootTuple } from './milestone-block';
import { durableAtomicWrite } from './durable-atomic-write';
import { findMergedDeliveryByPr } from './merged-delivery';

const FINISH_RANK: Partial<Record<FinishLine, number>> = { response: 0, artifact: 0, local_change: 1, review_receipt: 2, pr_open: 3, merged: 4, deployed: 5 };
const RECORDING_RANK = { response: 0, receipt: 1, session: 2, release: 3 } as const;
type RecordingLevel = keyof typeof RECORDING_RANK;
function hash(value: unknown): string { return new Bun.CryptoHasher('sha256').update(JSON.stringify(value)).digest('hex'); }
export interface CloseoutStatusInput { repoIds: string[]; requestedFinishLine: FinishLine; actualFinishLine: FinishLine; workKind: string; explicitClose: boolean; hasSession: boolean; terminalSubjectKey: string; proofIds: string[]; productProjectionHash: string; completionDate: string; missingCapabilityIds?: string[] }
export function resolveCloseoutStatus(profile: ParsedWorkProfile, input: CloseoutStatusInput) {
  if (input.requestedFinishLine === 'operation_result' && input.workKind !== 'operation') throw new Error('operation_work_kind_required');
  const requestedRank = FINISH_RANK[input.requestedFinishLine]; const actualRank = FINISH_RANK[input.actualFinishLine];
  if (requestedRank !== undefined && actualRank !== undefined && requestedRank < actualRank) throw new Error('finish_line_below_observed');
  const direct = profile.recording[input.requestedFinishLine]; const observed = profile.recording[input.actualFinishLine];
  let level = RECORDING_RANK[direct] >= RECORDING_RANK[observed] ? direct : observed;
  if (input.explicitClose) level = 'release';
  const reportRequired = level === 'release' || ['merged', 'deployed'].includes(input.actualFinishLine);
  const terminal = input.terminalSubjectKey; if (!/^[0-9a-f]{64}$/.test(terminal) || !/^\d{4}-\d{2}-\d{2}$/.test(input.completionDate)) throw new Error('closeout_subject_invalid');
  const expectedReportPath = reportRequired ? `docs/reports/${input.completionDate}-${terminal}-result.md` : null;
  const scopes = [...new Set(input.repoIds)].sort().map((repo_id) => ({ repo_id, paths: [...(input.hasSession && (level === 'session' || level === 'release') ? ['SESSION.md'] : []), ...(repo_id === [...new Set(input.repoIds)].sort()[0] && expectedReportPath ? [expectedReportPath] : [])].sort() })).filter((scope) => scope.paths.length);
  const preimage = { actual_finish_line: input.actualFinishLine, requested_finish_line: input.requestedFinishLine, recording_level: level, repo_ids: [...new Set(input.repoIds)].sort(), proof_ids: [...new Set(input.proofIds)].sort(), terminal_subject_key: terminal, product_projection_hash: input.productProjectionHash, allowed_recording_scopes: scopes, completion_date: input.completionDate };
  const bindingId = `recording-${hash(preimage).slice(0, 32)}`;
  const missing = [...new Set(input.missingCapabilityIds ?? [])].sort();
  return { ...preimage, proof_current: missing.length === 0, missing_capability_ids: missing, expected_report_path: expectedReportPath, recording_requirements: { session_required: input.hasSession && (level === 'session' || level === 'release'), report_required: reportRequired, eod_required: input.repoIds.length > 1 || input.explicitClose, binding_id: bindingId, binding_proof_ids: [...new Set(input.proofIds)].sort(), completion_date: input.completionDate }, binding_id: bindingId };
}

type TerminalSubjectKind = 'pr' | 'deploy_operation' | 'rollback_record';
export interface DerivedCloseoutInput { cwd: string; stateRoot: string; workKind: string; requestedFinishLine: FinishLine; lane: Lane; assertTargetRef?: string; assertTargetSha?: string; explicitClose?: boolean; assertProductHead?: string; terminalSubjectKind?: TerminalSubjectKind; terminalSubjectId?: string }
interface RecordingProjection { repo_id:string; paths:string[]; verified_hashes:Record<string,string>; projection_id:string; state:'verified'|'committed'|'terminal_abandoned'; commit_sha:string|null; abandonment_receipt_id?:string|null; residual_state_hash?:string|null }
interface RecordingBinding { schema: 'ecpe.recording-binding.v1'; status: 'prepared' | 'verified' | 'finalized'; result: ReturnType<typeof resolveCloseoutStatus> & Record<string, any>; repo_root: string; report_path: string; product_filesystem_hash: string; report_sha256: string | null; projections?:RecordingProjection[]; milestone_block_id?: string; target_terminal?: 'completed'|'partial_closed'; created_at: string; verified_at: string | null; finalized_at?:string|null }
function canonical(value: unknown): string { if (Array.isArray(value)) return `[${value.map(canonical).join(',')}]`; if (value && typeof value === 'object') { const row = value as Record<string, unknown>; return `{${Object.keys(row).sort().map((key) => `${JSON.stringify(key)}:${canonical(row[key])}`).join(',')}}`; } return JSON.stringify(value); }
function git(cwd: string, args: string[], code: string): string { const child = spawnSync('/usr/bin/git', args, { cwd, encoding: 'utf8', timeout: 20_000, shell: false, env: { PATH: '/usr/bin:/bin', LC_ALL: 'C', GIT_CONFIG_NOSYSTEM: '1' } }); if (child.status !== 0) throw new Error(code); return child.stdout.trim(); }
function completionDate(): string { return new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Seoul', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date()); }
function bytesHash(value:Uint8Array):string{return new Bun.CryptoHasher('sha256').update(value).digest('hex')}
function bindingFile(stateRoot: string, bindingId: string): string { if (!/^recording-[0-9a-f]{32}$/.test(bindingId)) throw new Error('recording_binding_invalid'); return path.join(path.resolve(stateRoot), 'ecpe', 'recording-bindings', `${bindingId}.json`); }
function readBinding(target:string):RecordingBinding{let value:RecordingBinding;try{const info=fs.lstatSync(target);if(!info.isFile()||info.isSymbolicLink()||(info.mode&0o077)!==0)throw new Error('recording_binding_invalid');value=JSON.parse(fs.readFileSync(target,'utf8'))}catch(error){if(error instanceof Error&&error.message==='recording_binding_invalid')throw error;throw new Error('recording_binding_missing')}if(value.schema!=='ecpe.recording-binding.v1'||typeof value.result?.binding_id!=='string'||path.basename(target)!==`${value.result.binding_id}.json`)throw new Error('recording_binding_invalid');return value}
function durableWrite(target: string, value: unknown): void { durableAtomicWrite(target, `${canonical(value)}\n`); }
function assertMilestoneCleanupCurrent(stateRoot:string,binding:RecordingBinding):void{if(!binding.milestone_block_id)return;const block=readMilestoneBlock(stateRoot,binding.milestone_block_id);if(!hasHarnessVerificationCleanupAck(block))throw new Error('verification_lineage_finalize_required')}
function productFilesystemHash(root: string, excluded: string[]): string {
  const skip = new Set(excluded); const rows: Array<[string, number, string]> = [];
  const visit = (directory: string, prefix: string) => { for (const entry of fs.readdirSync(directory, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) { if (!prefix && entry.name === '.git') continue; const relative = prefix ? `${prefix}/${entry.name}` : entry.name; if (skip.has(relative)) continue; const absolute = path.join(directory, entry.name); const info = fs.lstatSync(absolute); if (info.isSymbolicLink()) rows.push([relative, info.mode & 0o7777, `symlink:${fs.readlinkSync(absolute)}`]); else if (info.isDirectory()) visit(absolute, relative); else if (info.isFile()) rows.push([relative, info.mode & 0o7777, hash(fs.readFileSync(absolute))]); else throw new Error('recording_product_projection_invalid'); } };
  visit(root, ''); return hash(rows);
}
export function mergedReceiptMatchesCloseoutProduct(receipt:{repo_id:string;expected_head_oid:string;expected_head_tree:string;merge_sha:string;target_ref:string},input:{repoId:string;head:string;tree:string;targetSha:string;targetRef:string|null}):boolean{return input.targetRef!==null&&receipt.repo_id===input.repoId&&receipt.expected_head_oid===input.head&&receipt.expected_head_tree===input.tree&&receipt.merge_sha===input.targetSha&&receipt.target_ref===input.targetRef}
function shipProofs(stateRoot: string, cwd: string, repoId: string, head: string, tree:string,targetSha: string,targetRef:string|null, terminalSubjectKind?:TerminalSubjectKind, terminalSubjectId?:string): Array<{ id: string; finish: FinishLine }> {
  const identity = resolveProjectIdentity(cwd, { mode: 'profile' }); const rows = readJsonlUnion<any>(ledgerCandidates(identity, 'evidence', stateRoot)); const output: Array<{ id: string; finish: FinishLine }> = [];
  for (const row of rows) { if (row.schema_version !== 'ecpe.receipt.v2' || row.result !== 'pass' || row.subject?.repo_id !== repoId || row.subject?.local_head_sha !== head || row.subject?.base_sha !== targetSha || typeof row.run_id !== 'string') continue; if (row.capability?.id === 'delivery.pr_open' && row.handoff?.stage === 'ship') output.push({ id: row.run_id, finish: 'pr_open' }); else if (row.capability?.id === 'delivery.deployed') output.push({ id: row.run_id, finish: 'deployed' }); }
  if(terminalSubjectKind==='pr'&&terminalSubjectId&&/^[1-9][0-9]*$/.test(terminalSubjectId)){const merged=findMergedDeliveryByPr(stateRoot,repoId,Number(terminalSubjectId));if(merged&&mergedReceiptMatchesCloseoutProduct(merged,{repoId,head,tree,targetSha,targetRef}))output.push({id:merged.receipt_id,finish:'merged'})}
  return output;
}
function maximumFinish(base: FinishLine, proofs: Array<{ finish: FinishLine }>): FinishLine { let result = base; for (const proof of proofs) if ((FINISH_RANK[proof.finish] ?? -1) > (FINISH_RANK[result] ?? -1)) result = proof.finish; return result; }

export function deriveCurrentCloseoutStatus(input: DerivedCloseoutInput) {
  const cwd = fs.realpathSync(path.resolve(input.cwd)); const identity = resolveProjectIdentity(cwd, { mode: 'profile' }); const resolved = resolveTrustedWorkProfile({ cwd, lane: input.lane, assertTargetRef: input.assertTargetRef, assertTargetSha: input.assertTargetSha });
  if (!resolved.effective) throw new Error('trusted_profile_required'); const head = git(cwd, ['rev-parse', 'HEAD^{commit}'], 'closeout_git_failure'); if (input.assertProductHead && input.assertProductHead !== head) throw new Error('closeout_product_head_mismatch');
  const tree = git(cwd, ['rev-parse', 'HEAD^{tree}'], 'closeout_git_failure'); const dirty = git(cwd, ['status', '--porcelain=v1', '--untracked-files=all'], 'closeout_git_failure') !== ''; const manifest = buildChangeManifest({ cwd, profile: resolved.effective, targetBaseRef: resolved.trusted_base.target_ref ?? undefined, targetBaseSha: resolved.trusted_base.target_sha, mergeBaseSha: resolved.trusted_base.merge_base_sha });
  const deliveryProofs = shipProofs(input.stateRoot, cwd, identity.repo_id, head,tree,resolved.trusted_base.target_sha,resolved.trusted_base.target_ref,input.terminalSubjectKind,input.terminalSubjectId); let actual: FinishLine = head !== resolved.trusted_base.target_sha || dirty ? 'local_change' : 'response'; actual = maximumFinish(actual, deliveryProofs);
  const requirements = resolveProfileRequirements(resolved.effective, { roles: manifest.roles, lane: input.lane, finishLine: input.requestedFinishLine }); const proofIds = deliveryProofs.map((item) => item.id); const missing = [...requirements.unbound_capabilities];if((FINISH_RANK[input.requestedFinishLine]??-1)>=FINISH_RANK.merged&&!deliveryProofs.some(item=>item.finish==='merged'||item.finish==='deployed'))missing.push('delivery.merged');
  if (resolved.execution === 'profile') for (const validatorId of requirements.validator_ids) { try { const binding = resolveProfileValidatorBinding({ cwd, lane: input.lane, validatorId, assertTargetRef: input.assertTargetRef, assertTargetSha: input.assertTargetSha, stateHome: input.stateRoot, resolvedProfile: resolved }); const verdict = evaluateValidatorBinding(binding.binding); if (verdict.current && verdict.receipt_run_id) proofIds.push(verdict.receipt_run_id); else missing.push(binding.binding.evidenceContext.capability.id); } catch { missing.push(resolved.effective.validators[validatorId].capability); } }
  else for (const validatorId of requirements.validator_ids) missing.push(resolved.effective.validators[validatorId].capability);
  const explicit = input.explicitClose === true; const reportWillBeRequired = explicit || resolved.effective.recording[input.requestedFinishLine] === 'release' || resolved.effective.recording[actual] === 'release' || ['merged', 'deployed'].includes(actual);
  if (reportWillBeRequired && !explicit && (!input.terminalSubjectKind || !input.terminalSubjectId)) throw new Error('closeout_terminal_subject_required');
  if ((input.terminalSubjectKind === undefined) !== (input.terminalSubjectId === undefined) || (input.terminalSubjectKind && !['pr', 'deploy_operation', 'rollback_record'].includes(input.terminalSubjectKind)) || (input.terminalSubjectId && !/^[A-Za-z0-9][A-Za-z0-9._:-]{0,191}$/.test(input.terminalSubjectId))) throw new Error('closeout_terminal_subject_invalid');
  const terminalSubjectKey = hash({ repo_id: identity.repo_id, kind: input.terminalSubjectKind ?? 'explicit_close', id: input.terminalSubjectId ?? hash({ head, tree, target: resolved.trusted_base.target_sha, work_kind: input.workKind }), requested: input.requestedFinishLine });
  const result = resolveCloseoutStatus(resolved.effective, { repoIds: [identity.repo_id], requestedFinishLine: input.requestedFinishLine, actualFinishLine: actual, workKind: input.workKind, explicitClose: explicit, hasSession: fs.existsSync(path.join(cwd, 'SESSION.md')), terminalSubjectKey, proofIds, productProjectionHash: hash({ repo_id: identity.repo_id, head, tree, wtree: manifest.wtree, manifest_hash: manifest.manifest_hash }), completionDate: completionDate(), missingCapabilityIds: missing });
  return { ...result, lane: input.lane, lane_activation: resolved.lane_activation, trusted_profile_state: resolved.candidate_state, terminal_subject_key: terminalSubjectKey, report_deferred: false, allowed_recording_scopes: result.allowed_recording_scopes, product_projection_hash: result.product_projection_hash, disposition: result.expected_report_path ? 'prepare_required' as const : result.proof_current ? 'recording_not_required' as const : 'proof_missing' as const };
}

export function prepareCurrentCloseout(input: DerivedCloseoutInput & { assertReportPath: string }) {
  const result = deriveCurrentCloseoutStatus(input); if (!result.recording_requirements.report_required || !result.expected_report_path) throw new Error('closeout_report_not_required'); if (input.assertReportPath !== result.expected_report_path) throw new Error('closeout_report_path_mismatch'); if (!result.proof_current) throw new Error(`closeout_proof_missing:${result.missing_capability_ids.join(',')}`);
  const root = fs.realpathSync(path.resolve(input.cwd)); const report = path.resolve(root, input.assertReportPath); if (!report.startsWith(`${root}${path.sep}`) || fs.existsSync(report)) throw new Error('closeout_report_path_unavailable'); const target = bindingFile(input.stateRoot, result.binding_id);
  const excluded = result.allowed_recording_scopes.flatMap((scope) => scope.paths); const binding: RecordingBinding = { schema: 'ecpe.recording-binding.v1', status: 'prepared', result, repo_root: root, report_path: input.assertReportPath, product_filesystem_hash: productFilesystemHash(root, excluded), report_sha256: null, created_at: new Date().toISOString(), verified_at: null };
  if (fs.existsSync(target)) { const existing = JSON.parse(fs.readFileSync(target, 'utf8')) as RecordingBinding; if (canonical(existing.result) !== canonical(result) || existing.repo_root !== root || existing.report_path !== input.assertReportPath) throw new Error('recording_binding_conflict'); return { ...result, disposition: existing.status === 'verified' ? 'recording_pending' as const : 'prepared' as const, binding_id: result.binding_id, report_binding_block: { binding_id: result.binding_id, proof_ids: result.proof_ids, product_projection_hash: result.product_projection_hash, terminal_subject_key: result.terminal_subject_key } }; }
  durableWrite(target, binding); return { ...result, disposition: 'prepared' as const, binding_id: result.binding_id, report_binding_block: { binding_id: result.binding_id, proof_ids: result.proof_ids, product_projection_hash: result.product_projection_hash, terminal_subject_key: result.terminal_subject_key } };
}

export function verifyCurrentRecording(input: { stateRoot: string; cwd: string; bindingId: string; reportPath: string }) {
  const target = bindingFile(input.stateRoot, input.bindingId); let binding: RecordingBinding; try { binding = JSON.parse(fs.readFileSync(target, 'utf8')); } catch { throw new Error('recording_binding_missing'); }
  if (binding.schema !== 'ecpe.recording-binding.v1' || binding.result.binding_id !== input.bindingId || binding.report_path !== input.reportPath || fs.realpathSync(path.resolve(input.cwd)) !== binding.repo_root) throw new Error('recording_binding_mismatch');
  assertMilestoneCleanupCurrent(input.stateRoot,binding);
  const report = path.resolve(binding.repo_root, input.reportPath); if (!report.startsWith(`${binding.repo_root}${path.sep}`)) throw new Error('recording_report_path_invalid'); const info = fs.lstatSync(report); if (!info.isFile() || info.isSymbolicLink()) throw new Error('recording_report_invalid'); const bytes = fs.readFileSync(report); const text = bytes.toString('utf8'); const begin = '=== ECPE_RECORDING_BINDING_BEGIN ==='; const end = '=== ECPE_RECORDING_BINDING_END ==='; const start = text.indexOf(begin); const finish = text.indexOf(end); if (start < 0 || finish <= start || text.indexOf(begin, start + begin.length) >= 0 || text.indexOf(end, finish + end.length) >= 0) throw new Error('recording_binding_block_missing');
  const excluded = binding.result.allowed_recording_scopes.flatMap((scope) => scope.paths); if (productFilesystemHash(binding.repo_root, excluded) !== binding.product_filesystem_hash) throw new Error('prepared_owner_drift');
  let block: unknown; try { block = JSON.parse(text.slice(start + begin.length, finish).trim()); } catch { throw new Error('recording_binding_block_invalid'); } const expected = { binding_id: binding.result.binding_id, proof_ids: binding.result.proof_ids, product_projection_hash: binding.result.product_projection_hash, terminal_subject_key: (binding.result as any).terminal_subject_key }; if (canonical(block) !== canonical(expected)) throw new Error('recording_binding_block_mismatch');
  const reportHash = hash(bytes); if (binding.status === 'verified'||binding.status==='finalized') { if (binding.report_sha256 !== reportHash) throw new Error('recording_report_changed'); return { disposition: 'reused' as const, binding_id: input.bindingId, report_sha256: reportHash, recording_pending: binding.status==='verified', finalized:binding.status==='finalized', ...(binding.milestone_block_id?{milestone_block_id:binding.milestone_block_id,target_terminal:binding.target_terminal}:{}) }; }
  binding.status = 'verified'; binding.report_sha256 = reportHash; binding.verified_at = new Date().toISOString();binding.projections=binding.result.allowed_recording_scopes.map((scope:{repo_id:string;paths:string[]})=>{const verifiedHashes:Record<string,string>={};for(const relative of scope.paths){const absolute=path.resolve(binding.repo_root,relative);if(!absolute.startsWith(`${binding.repo_root}${path.sep}`))throw new Error('recording_projection_path_invalid');const item=fs.lstatSync(absolute);if(!item.isFile()||item.isSymbolicLink())throw new Error('recording_projection_file_invalid');verifiedHashes[relative]=bytesHash(fs.readFileSync(absolute))}const projectionId=`recording-projection-${hash({binding_id:input.bindingId,repo_id:scope.repo_id,paths:[...scope.paths],verified_hashes:verifiedHashes}).slice(0,32)}`;return{repo_id:scope.repo_id,paths:[...scope.paths],verified_hashes:verifiedHashes,projection_id:projectionId,state:'verified' as const,commit_sha:null,abandonment_receipt_id:null,residual_state_hash:null}}); durableWrite(target, binding); if(binding.milestone_block_id&&binding.target_terminal)updateMilestoneBlock(input.stateRoot,binding.milestone_block_id,(block)=>{if(!['closing_final','recording_pending'].includes(block.phase))throw new Error('milestone_recording_phase_invalid');block.phase='recording_pending';return null}); return { disposition: 'verified' as const, binding_id: input.bindingId, report_sha256: reportHash, recording_pending: true, ...(binding.milestone_block_id?{milestone_block_id:binding.milestone_block_id,target_terminal:binding.target_terminal}:{}) };
}

function recordingIndexPreimage(root:string):string{const head=git(root,['rev-parse','HEAD^{commit}'],'recording_projection_git_invalid');const index=spawnSync('/usr/bin/git',['ls-files','--stage','-z'],{cwd:root,encoding:null,shell:false,env:{PATH:'/usr/bin:/bin',LC_ALL:'C',GIT_CONFIG_NOSYSTEM:'1'}});if(index.status!==0)throw new Error('recording_projection_git_invalid');return hash({head,index_sha256:bytesHash(index.stdout)})}
function finalizeRecordingBinding(input:{stateRoot:string;target:string;binding:RecordingBinding}):void{const terminal=input.binding.projections?.every(item=>item.state==='committed'||item.state==='terminal_abandoned')??false;if(!terminal)return;assertMilestoneCleanupCurrent(input.stateRoot,input.binding);input.binding.status='finalized';input.binding.finalized_at=input.binding.finalized_at??new Date().toISOString();if(input.binding.milestone_block_id&&input.binding.target_terminal)updateMilestoneBlock(input.stateRoot,input.binding.milestone_block_id,(block)=>{if(!hasHarnessVerificationCleanupAck(block))throw new Error('verification_lineage_finalize_required');if(block.phase===input.binding.target_terminal)return null;if(block.phase!=='recording_pending')throw new Error('milestone_recording_phase_invalid');block.phase=input.binding.target_terminal!;return null})}
export function inspectRecordingTerminal(input:{stateRoot:string;cwd:string;bindingId:string;repoId?:string}){const target=bindingFile(input.stateRoot,input.bindingId);let binding:RecordingBinding;try{binding=JSON.parse(fs.readFileSync(target,'utf8'))}catch{throw new Error('recording_binding_missing')}if(binding.schema!=='ecpe.recording-binding.v1'||binding.result.binding_id!==input.bindingId||fs.realpathSync(path.resolve(input.cwd))!==binding.repo_root)throw new Error('recording_binding_mismatch');if(binding.status==='prepared')return{result:'prepared',binding_id:input.bindingId,next_operation:'recording_verify'};if(!binding.projections?.length)throw new Error('recording_projection_missing');if(input.repoId&&binding.projections.filter(item=>item.repo_id===input.repoId).length!==1)throw new Error('recording_projection_mismatch');let changed=false;for(const projection of binding.projections){if(projection.state!=='verified')continue;const status=spawnSync('/usr/bin/git',['status','--porcelain=v1','--untracked-files=all','--',...projection.paths],{cwd:binding.repo_root,encoding:'utf8',shell:false,env:{PATH:'/usr/bin:/bin',LC_ALL:'C',GIT_CONFIG_NOSYSTEM:'1'}});if(status.status!==0)throw new Error('recording_projection_git_invalid');if(status.stdout.trim())continue;let current=true;for(const relative of projection.paths){const shown=spawnSync('/usr/bin/git',['show',`HEAD:${relative}`],{cwd:binding.repo_root,encoding:null,shell:false,env:{PATH:'/usr/bin:/bin',LC_ALL:'C',GIT_CONFIG_NOSYSTEM:'1'}});if(shown.status!==0||bytesHash(shown.stdout)!==projection.verified_hashes[relative]){current=false;break}}if(current){projection.state='committed';projection.commit_sha=git(binding.repo_root,['rev-parse','HEAD^{commit}'],'recording_projection_git_invalid');changed=true}}
  finalizeRecordingBinding({stateRoot:input.stateRoot,target,binding});if(binding.status==='finalized')changed=true;if(changed)durableWrite(target,binding);const selected=input.repoId?binding.projections.filter(item=>item.repo_id===input.repoId):binding.projections;const indexClean=spawnSync('/usr/bin/git',['diff','--cached','--quiet','--exit-code'],{cwd:binding.repo_root,stdio:'ignore',shell:false,env:{PATH:'/usr/bin:/bin',LC_ALL:'C',GIT_CONFIG_NOSYSTEM:'1'}}).status===0;return{result:binding.status==='finalized'?'finalized':'recording_pending',binding_id:input.bindingId,projections:selected.map(item=>({repo_id:item.repo_id,state:item.state,commit_sha:item.commit_sha,verified_recording_projection_id:item.projection_id,abandonment_receipt_id:item.abandonment_receipt_id??null,...(item.state==='verified'&&indexClean?{recording_closeout_gate:item.projection_id,index_preimage:recordingIndexPreimage(binding.repo_root)}:{})})),target_terminal:binding.target_terminal??null,milestone_block_id:binding.milestone_block_id??null,next_operation:binding.status==='finalized'?'none':'recording_projection_dispose'}}

export function abandonRecordingProjection(input:{stateRoot:string;cwd:string;bindingId:string;repoId:string;assertGate:string;assertIndexPreimage:string}){const target=bindingFile(input.stateRoot,input.bindingId);let binding:RecordingBinding;try{binding=JSON.parse(fs.readFileSync(target,'utf8'))}catch{throw new Error('recording_binding_missing')}if(binding.schema!=='ecpe.recording-binding.v1'||binding.result.binding_id!==input.bindingId||!['verified','finalized'].includes(binding.status)||fs.realpathSync(path.resolve(input.cwd))!==binding.repo_root||!binding.projections)throw new Error('recording_binding_mismatch');const matches=binding.projections.filter(item=>item.repo_id===input.repoId);if(matches.length!==1)throw new Error('recording_projection_mismatch');const projection=matches[0];if(projection.state==='terminal_abandoned'){if(projection.projection_id===input.assertGate)return{result:'reused',binding_id:input.bindingId,repo_id:input.repoId,disposition:'terminal_abandoned',abandonment_receipt_id:projection.abandonment_receipt_id,next_operation:binding.status==='finalized'?'none':'recording_projection_dispose'};throw new Error('recording_projection_terminal')}if(binding.status!=='verified'||projection.state!=='verified'||projection.projection_id!==input.assertGate)throw new Error('recording_projection_gate_mismatch');const clean=spawnSync('/usr/bin/git',['diff','--cached','--quiet','--exit-code'],{cwd:binding.repo_root,stdio:'ignore',shell:false,env:{PATH:'/usr/bin:/bin',LC_ALL:'C',GIT_CONFIG_NOSYSTEM:'1'}});if(clean.status!==0)throw new Error('recording_index_not_clean');const preimage=recordingIndexPreimage(binding.repo_root);if(preimage!==input.assertIndexPreimage)throw new Error('recording_index_preimage_mismatch');const residual=spawnSync('/usr/bin/git',['status','--porcelain=v1','-z','--untracked-files=all'],{cwd:binding.repo_root,encoding:null,shell:false,env:{PATH:'/usr/bin:/bin',LC_ALL:'C',GIT_CONFIG_NOSYSTEM:'1'}});if(residual.status!==0)throw new Error('recording_projection_git_invalid');const residualHash=bytesHash(residual.stdout);const receipt=`recording-abandon-${hash({binding_id:input.bindingId,repo_id:input.repoId,projection_id:projection.projection_id,index_preimage:preimage,residual_state_hash:residualHash,reason:'explicit_uncommitted_disposition'}).slice(0,32)}`;projection.state='terminal_abandoned';projection.abandonment_receipt_id=receipt;projection.residual_state_hash=residualHash;finalizeRecordingBinding({stateRoot:input.stateRoot,target,binding});durableWrite(target,binding);return{result:'abandoned',binding_id:input.bindingId,repo_id:input.repoId,disposition:'terminal_abandoned',reason:'explicit_uncommitted_disposition',abandonment_receipt_id:receipt,next_operation:binding.status==='finalized'?'none':'recording_projection_dispose'}}

export function inspectRecordingBinding(input:{stateRoot:string;cwd?:string;bindingId?:string;blockId?:string;purpose?:'ecpe-v3-pilot';currentProject?:boolean}){const selectors=[Boolean(input.bindingId),Boolean(input.blockId),Boolean(input.purpose),Boolean(input.currentProject)].filter(Boolean).length;if(selectors!==1)throw new Error('recording_binding_selector_invalid');const directory=path.join(path.resolve(input.stateRoot),'ecpe','recording-bindings');let files:string[]=[];try{files=fs.readdirSync(directory).filter(name=>/^recording-[0-9a-f]{32}\.json$/.test(name)).map(name=>path.join(directory,name))}catch{}let bindings=files.map(readBinding);if(input.bindingId)bindings=bindings.filter(item=>item.result.binding_id===input.bindingId);if(input.blockId)bindings=bindings.filter(item=>item.milestone_block_id===input.blockId);if(input.purpose)bindings=bindings.filter(item=>Boolean(item.milestone_block_id));if(input.currentProject){if(!input.cwd)throw new Error('recording_binding_selector_invalid');const root=fs.realpathSync(path.resolve(input.cwd));bindings=bindings.filter(item=>item.repo_root===root)}const live=bindings.filter(item=>item.status!=='finalized');const selected=live.length===1?live[0]:live.length>1?null:bindings.sort((a,b)=>(b.finalized_at??b.verified_at??b.created_at).localeCompare(a.finalized_at??a.verified_at??a.created_at))[0];if(!selected)throw new Error(live.length>1?'recording_binding_ambiguous':'recording_binding_missing');const projections=(selected.projections??[]).map(item=>({repo_id:item.repo_id,state:item.state,verified_recording_projection_id:item.projection_id??null,commit_sha:item.commit_sha,abandonment_receipt_id:item.abandonment_receipt_id??null}));return{schema:'ecpe.recording-binding-inspect.v1',state:selected.status==='prepared'?'prepared':selected.status==='verified'?'recording_commit_pending':'finalized',binding_id:selected.result.binding_id,milestone_block_id:selected.milestone_block_id??null,verdict:selected.target_terminal??null,completion_date:selected.result.completion_date,expected_report_path:selected.report_path,proof_ids:selected.result.proof_ids,product_projection_hash:selected.result.product_projection_hash,projections,...(selected.status==='finalized'?{}:{allowed_recording_scopes:selected.result.allowed_recording_scopes,report_binding_block:{binding_id:selected.result.binding_id,proof_ids:selected.result.proof_ids,product_projection_hash:selected.result.product_projection_hash,terminal_subject_key:selected.result.terminal_subject_key}}),next_operation:selected.status==='prepared'?'recording_verify':selected.status==='verified'?'recording_terminal_inspect':'none'}}

export function milestoneCloseoutLandingProjection(landings:DurableMilestoneLanding[]=[]){
  if(landings.some(landing=>landing.phase!=='checkpointed'))throw new Error('milestone_landing_reconciliation_required');
  return [...landings].sort((left,right)=>left.sequence-right.sequence).map(landing=>({
    sequence:landing.sequence,landing_id:landing.landing_id,kind:landing.kind,repository_node_id:landing.repository_node_id,pr:landing.pr,
    expected_base_oid:landing.expected_base_oid,expected_head_oid:landing.expected_head_oid,target_ref:landing.target_ref,subject_tree:landing.subject_tree,
    raw_provider_intent_id:landing.raw_provider_intent_id,ship_receipt_id:landing.ship_receipt_id,lanes:landing.lanes,
    merge_sha:landing.merge_sha,delivery_receipt_id:landing.delivery_receipt_id,delivery_receipt_binding_sha256:landing.delivery_receipt_binding_sha256,
    landing_checkpoint_id:landing.landing_checkpoint_id,landing_checkpoint_binding_sha256:landing.landing_checkpoint_binding_sha256,
    release_drift_status:landing.release_drift_status,checkpoint_event_hash:landing.checkpoint_event_hash,provider_base_atomicity:'observed_only' as const,
  }));
}

export function prepareMilestoneCloseout(input:{stateRoot:string;ownerRoot:string;ownerRepoId:string;roots:MilestoneRootTuple;blockId:string;workKind:string;requestedFinishLine:FinishLine;assertReportPath:string;partial:boolean}){
  const block=readMilestoneBlock(input.stateRoot,input.blockId);if(canonical(block.roots)!==canonical(input.roots))throw new Error('milestone_root_mismatch');if(!hasHarnessVerificationCleanupAck(block))throw new Error('verification_lineage_finalize_required');if(!['terminal_unreported','closing_final','recording_pending'].includes(block.phase))throw new Error('milestone_closeout_phase_invalid');const terminalized=Boolean(block.terminal_reason)||block.slot?.state==='terminalized';if(input.partial!==terminalized)throw new Error('milestone_closeout_kind_mismatch');if(!terminalized&&block.slot?.state!=='complete')throw new Error('milestone_evaluation_incomplete');
  const owner=fs.realpathSync(path.resolve(input.ownerRoot));const terminalAt=block.terminal_at??block.slot?.cutoff_at;if(!terminalAt)throw new Error('milestone_terminal_time_missing');const date=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(terminalAt));const reportKey=milestoneBlockReportKey(input.ownerRepoId,block.block_id);const expectedReportPath=`docs/reports/${date}-ecpe-v3-pilot-${reportKey}-result.md`;if(input.assertReportPath!==expectedReportPath)throw new Error('closeout_report_path_mismatch');const report=path.resolve(owner,expectedReportPath);if(!report.startsWith(`${owner}${path.sep}`)||(block.phase==='terminal_unreported'&&fs.existsSync(report)))throw new Error('closeout_report_path_unavailable');
  const landingProjection=milestoneCloseoutLandingProjection(block.landings);
  const landingProofIds=landingProjection.flatMap(landing=>[landing.ship_receipt_id,landing.delivery_receipt_id,landing.landing_checkpoint_id]).filter((value):value is string=>Boolean(value));
  const proofIds=[...(block.slot?.positions.map(position=>position.proof_id).filter((value):value is string=>Boolean(value))??[]),...(block.slot?.evaluation_proof_id?[block.slot.evaluation_proof_id]:[]),...landingProofIds].sort();const allowed=[{repo_id:input.ownerRepoId,paths:[expectedReportPath,'dev/active/EOD_Finalize.md'].sort()}];const productProjectionHash=hash({block_id:block.block_id,code_root_head:block.code_root_head,registry_hash:block.registry_hash,slot:block.slot?.slot_id??null,proof_ids:proofIds,landings:landingProjection});const preimage={actual_finish_line:'verified' as FinishLine,requested_finish_line:input.requestedFinishLine,recording_level:'release' as const,repo_ids:[input.ownerRepoId],proof_ids:proofIds,terminal_subject_key:reportKey,product_projection_hash:productProjectionHash,allowed_recording_scopes:allowed,completion_date:date,verdict:input.partial?'partial':'completed',terminal_reason:block.terminal_reason};const bindingId=`recording-${hash(preimage).slice(0,32)}`;const result={...preimage,proof_current:true,missing_capability_ids:[],expected_report_path:expectedReportPath,recording_requirements:{session_required:false,report_required:true,eod_required:true,binding_id:bindingId,binding_proof_ids:proofIds,completion_date:date},binding_id:bindingId,lane:'cross_repo_contract',lane_activation:'legacy',trusted_profile_state:'milestone_frozen',terminal_subject_key:reportKey,report_deferred:false,disposition:'prepared'} as any;const target=bindingFile(input.stateRoot,bindingId);const binding:RecordingBinding={schema:'ecpe.recording-binding.v1',status:'prepared',result,repo_root:owner,report_path:expectedReportPath,product_filesystem_hash:productFilesystemHash(owner,allowed[0].paths),report_sha256:null,milestone_block_id:block.block_id,target_terminal:input.partial?'partial_closed':'completed',created_at:new Date().toISOString(),verified_at:null};
  if(fs.existsSync(target)){const existing=JSON.parse(fs.readFileSync(target,'utf8'))as RecordingBinding;if(canonical(existing.result)!==canonical(result)||existing.repo_root!==owner)throw new Error('recording_binding_conflict');return{...result,disposition:existing.status==='verified'?'recording_pending':'reused',report_binding_block:{binding_id:bindingId,proof_ids:proofIds,product_projection_hash:productProjectionHash,terminal_subject_key:reportKey}}}
  durableWrite(target,binding);try{updateMilestoneBlock(input.stateRoot,block.block_id,current=>{if(current.phase!=='terminal_unreported')throw new Error('milestone_closeout_phase_invalid');if(!hasHarnessVerificationCleanupAck(current))throw new Error('verification_lineage_finalize_required');current.phase='closing_final';return null})}catch(error){try{fs.unlinkSync(target)}catch{}throw error}return{...result,report_binding_block:{binding_id:bindingId,proof_ids:proofIds,product_projection_hash:productProjectionHash,terminal_subject_key:reportKey}};
}

export interface CloseJournalEntry { sequence: number; previous_hash: string | null; kind: string; subject_id: string; payload_hash: string; entry_hash: string }
export function appendCloseJournal(entries: CloseJournalEntry[], input: { kind: string; subjectId: string; payload: unknown }): CloseJournalEntry[] {
  if (!/^[a-z][a-z0-9._-]*$/.test(input.kind) || !input.subjectId) throw new Error('close_journal_input_invalid');
  verifyCloseJournal(entries); const body = { sequence: entries.length, previous_hash: entries.at(-1)?.entry_hash ?? null, kind: input.kind, subject_id: input.subjectId, payload_hash: hash(input.payload) }; const next = { ...body, entry_hash: hash(body) }; return [...entries, next];
}
export function verifyCloseJournal(entries: CloseJournalEntry[]): void { let previous: string | null = null; for (let index = 0; index < entries.length; index++) { const entry = entries[index]; const { entry_hash, ...body } = entry; if (entry.sequence !== index || entry.previous_hash !== previous || hash(body) !== entry_hash) throw new Error('close_journal_corrupt'); previous = entry_hash; } }
