import type { ProofPositionState,ProofTerminalKind } from './milestone-block';
export interface ParticipantPosition{participant:string;state:ProofPositionState;proof_id:string|null;terminal_kind:ProofTerminalKind|null}
export function attachParticipantProof(position:ParticipantPosition,proofId:string):ParticipantPosition{if(!['empty','producer_reserved','result_captured','retryable_ambiguous'].includes(position.state)||position.proof_id||!proofId)throw new Error('participant_proof_already_resolved');return {...position,state:'attached',proof_id:proofId,terminal_kind:null}}
export function terminalizeParticipant(position:ParticipantPosition,kind:ProofTerminalKind):ParticipantPosition{if(position.state==='attached'||position.state==='terminalized'||position.proof_id)throw new Error('participant_proof_already_resolved');return {...position,state:'terminalized',proof_id:null,terminal_kind:kind}}

import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { spawnSync } from 'node:child_process';
import { legacyValidatorDescriptor } from './legacy-validator';
import { findMilestoneBlockBySlot } from './milestone-block';
import { attachPilotParticipant } from './pilot-evaluation';
import { materializePrivateValidatorEnv, releasePrivateValidatorEnv } from './private-validator-env';
import { releaseRuntimeBinding, resolveRegisteredRuntimeBinding, resolveRuntimeBinding } from './validator-runtime';
import { durableAtomicWrite } from './durable-atomic-write';

const digest=(value:string|Uint8Array)=>new Bun.CryptoHasher('sha256').update(value).digest('hex');
function canonical(value:unknown):string{if(Array.isArray(value))return`[${value.map(canonical).join(',')}]`;if(value&&typeof value==='object'){const row=value as Record<string,unknown>;return`{${Object.keys(row).sort().map(key=>`${JSON.stringify(key)}:${canonical(row[key])}`).join(',')}}`;}return JSON.stringify(value)}
function git(cwd:string,args:string[],code:string):string{const child=spawnSync('/usr/bin/git',args,{cwd,encoding:'utf8',timeout:30_000,shell:false,env:{PATH:'/usr/bin:/bin',HOME:os.homedir(),LC_ALL:'C',GIT_CONFIG_NOSYSTEM:'1'}});if(child.status!==0)throw new Error(code);return child.stdout.trim()}
function proofFile(stateRoot:string,proofId:string):string{return path.join(path.resolve(stateRoot),'ecpe','milestones','proofs',`${proofId}.json`)}
function durableWrite(target:string,value:unknown):void{durableAtomicWrite(target,`${canonical(value)}\n`)}
export function verifyFrozenMilestoneParticipant(input:{stateRoot:string;slotId:string;participant:'portfolioops'|'harness-governance';repositoryRoot:string;registryHash?:string;runtimeManifestPath?:string}){
  const block=findMilestoneBlockBySlot(input.stateRoot,input.slotId);const slot=block.slot!;const position=slot.positions.find(item=>item.participant===input.participant);if(!position)throw new Error('participant_position_missing');if(position.state==='attached')return{disposition:'receipt_current' as const,proof_id:position.proof_id,next_operation:'pilot_evaluation_inspect'};if(position.state==='terminalized')return{disposition:'terminalized' as const,terminal_kind:position.terminal_kind,proof_id:null,next_operation:'milestone_block_inspect_for_partial'};
  const root=fs.realpathSync(path.resolve(input.repositoryRoot));const head=git(root,['rev-parse','HEAD^{commit}'],'participant_subject_invalid');const tree=git(root,['rev-parse','HEAD^{tree}'],'participant_subject_invalid');const subjectHash=input.participant==='portfolioops'?digest(`${head}\0${tree}`):digest(`${head}\0${tree}\0${input.registryHash??''}`);if(slot.participant_subject_hashes[input.participant]!==subjectHash)throw new Error('participant_subject_moved');
  const privateSubject=materializePrivateValidatorEnv({sourceRepository:root,subjectSha:head});let runtime:{lease_root:string;argv:string[];environment:Record<string,string>}|null=null;let exit=1;let terminal:ProofTerminalKind|null=null;let validatorId='';
  try{if(input.participant==='portfolioops'){const descriptor=legacyValidatorDescriptor('portfolioops','full');validatorId='portfolioops.full';runtime=resolveRuntimeBinding({repositoryRoot:root,interpreterRelpath:descriptor.interpreter_relpath!,lockfiles:descriptor.lockfiles!,sourceRoots:descriptor.source_roots,binding:descriptor.runtime_binding!,argv:descriptor.argv});const executable=path.join(privateSubject.checkout_root,descriptor.argv[0]);const info=fs.lstatSync(executable);if(!info.isFile()||info.isSymbolicLink()||(info.mode&0o111)===0)throw new Error('participant_validator_invalid');const before=git(privateSubject.checkout_root,['status','--porcelain=v1','--untracked-files=all'],'participant_subject_invalid');const child=spawnSync(executable,[],{cwd:privateSubject.checkout_root,shell:false,stdio:'inherit',timeout:600_000,env:{...privateSubject.environment,...runtime.environment,PYTHONPATH:descriptor.source_roots.map(relative=>path.join(privateSubject.checkout_root,relative)).join(path.delimiter)}});exit=child.status??1;const after=git(privateSubject.checkout_root,['status','--porcelain=v1','--untracked-files=all'],'participant_subject_invalid');if(before!==''||after!==''||git(privateSubject.checkout_root,['rev-parse','HEAD^{commit}'],'participant_subject_invalid')!==head)throw new Error('participant_subject_mutated');}
    else{const descriptor=legacyValidatorDescriptor('harness','harness.t4');validatorId='harness.t4';runtime=resolveRegisteredRuntimeBinding({repositoryRoot:privateSubject.checkout_root,runtimeId:'harness_test_python',manifestPath:input.runtimeManifestPath,sourceRoots:['.'],binding:{mode:'argv0'},argv:['python',...descriptor.argv.slice(1)]});const before=git(privateSubject.checkout_root,['status','--porcelain=v1','--untracked-files=all'],'participant_subject_invalid');const child=spawnSync(runtime.argv[0],runtime.argv.slice(1),{cwd:privateSubject.checkout_root,shell:false,stdio:'inherit',timeout:600_000,env:{...privateSubject.environment,...runtime.environment,PYTHONPATH:privateSubject.checkout_root}});exit=child.status??1;const after=git(privateSubject.checkout_root,['status','--porcelain=v1','--untracked-files=all'],'participant_subject_invalid');if(before!==''||after!==''||git(privateSubject.checkout_root,['rev-parse','HEAD^{commit}'],'participant_subject_invalid')!==head)throw new Error('participant_subject_mutated');}}
  catch(error){terminal=error instanceof Error&&['runtime_input_missing','registered_runtime_manifest_missing','registered_runtime_attestation_failed'].some(code=>error.message.includes(code))?'participant_unavailable':'safety_failure'}finally{if(runtime)releaseRuntimeBinding(runtime);releasePrivateValidatorEnv(privateSubject)}
  if(git(root,['rev-parse','HEAD^{commit}'],'participant_subject_invalid')!==head)throw new Error('participant_subject_moved');if(exit!==0&&!terminal)terminal='safety_failure';if(terminal){const attached=attachPilotParticipant({stateRoot:input.stateRoot,blockId:block.block_id,slotId:input.slotId,participant:input.participant,terminalKind:terminal});return{disposition:'terminalized' as const,terminal_kind:terminal,proof_id:null,next_operation:attached.next_operation}}
  const body={schema:'ecpe.milestone-participant-proof.v1',block_id:block.block_id,evaluation_slot_id:input.slotId,participant:input.participant,validator_id:validatorId,subject_head_sha:head,subject_tree_sha:tree,subject_hash:subjectHash,result:'pass',exit:0};const proofId=`participant-proof-${digest(canonical(body)).slice(0,32)}`;const target=proofFile(input.stateRoot,proofId);if(fs.existsSync(target)){const existing=JSON.parse(fs.readFileSync(target,'utf8'));if(canonical(existing)!==canonical({...body,proof_id:proofId}))throw new Error('participant_proof_conflict')}else durableWrite(target,{...body,proof_id:proofId});const attached=attachPilotParticipant({stateRoot:input.stateRoot,blockId:block.block_id,slotId:input.slotId,participant:input.participant,proofId});return{disposition:'attached' as const,proof_id:proofId,subject_head_sha:head,subject_tree_sha:tree,next_operation:attached.next_operation};
}
