import * as fs from 'node:fs';import * as os from 'node:os';import * as path from 'node:path';import { spawnSync } from 'node:child_process';
import { inspectLanePromotionAssessment, type PromotionLane } from './lane-promotion';import { parseWorkProfile } from './work-profile';
import { durableAtomicWrite } from './durable-atomic-write';
import { acquireDurableOwnerLock, releaseDurableOwnerLock } from './durable-owner-lock';
type Intent={schema:'ecpe.profile-promotion-intent.v1';phase:'prepared'|'written';proof_id:string;block_id:string;participant:'portfolioops';lane:PromotionLane;selector:string;subject_head:string;subject_tree:string;before_sha256:string;after_sha256:string;before_profile_hash:string;after_profile_hash:string;record_id:string|null};
export interface ProfilePromotionLineage{block_id:string;lane:PromotionLane;proof_id:string;record_id:string;before_profile_hash:string;after_profile_hash:string;before_sha256:string;after_sha256:string;subject_head:string;subject_tree:string}
const digest=(value:string|Uint8Array)=>new Bun.CryptoHasher('sha256').update(value).digest('hex');
function git(cwd:string,args:string[],code:string):string{const child=spawnSync('/usr/bin/git',args,{cwd,encoding:'utf8',shell:false,env:{PATH:'/usr/bin:/bin',HOME:os.homedir(),LC_ALL:'C',GIT_CONFIG_NOSYSTEM:'1'}});if(child.status!==0)throw new Error(code);return child.stdout.trim()}
function target(stateRoot:string,blockId:string,lane:PromotionLane){return path.join(path.resolve(stateRoot),'ecpe','profile-promotion-intents',`${blockId}-${lane}.json`)}
function write(targetPath:string,value:Intent){durableAtomicWrite(targetPath,JSON.stringify(value)+'\n')}
function withPromotionLock<T>(stateRoot:string,proofId:string,lane:PromotionLane,callback:()=>T):T{if(!/^promotion-[0-9a-f]{32}$/.test(proofId))throw new Error('promotion_proof_invalid');const lock=path.join(path.resolve(stateRoot),'ecpe','profile-promotion-intents',`.${proofId}-${lane}`);const owned=acquireDurableOwnerLock(lock,'promotion_owner_busy');try{return callback()}finally{releaseDurableOwnerLock(owned)}}
function promotedBytes(source:string,lane:PromotionLane):string{const lines=source.split(/(?<=\n)/);let inLanes=false,inLane=false,seen=0;for(let index=0;index<lines.length;index++){const text=lines[index].replace(/\r?\n$/,'');if(/^lanes:\s*$/.test(text)){inLanes=true;inLane=false;continue}if(inLanes&&/^\S/.test(text)&&text.trim()){inLanes=false;inLane=false}if(inLanes&&new RegExp(`^  ${lane}:\\s*\\{.*\\bactivation:\\s*shadow\\b`).test(text)){lines[index]=lines[index].replace(/\bactivation:\s*shadow\b/,'activation: enforce');seen++;continue}if(inLanes&&new RegExp(`^  ${lane}:\\s*$`).test(text)){inLane=true;continue}if(inLane&&/^  \S/.test(text)&&!new RegExp(`^  ${lane}:`).test(text)){inLane=false}if(inLane&&/^    activation:\s*shadow\s*$/.test(text)){const ending=lines[index].endsWith('\r\n')?'\r\n':lines[index].endsWith('\n')?'\n':'';lines[index]=`    activation: enforce${ending}`;seen++}}if(seen!==1)throw new Error('promotion_selector_mismatch');return lines.join('')}
function loadIntent(stateRoot:string,blockId:string,lane:PromotionLane):Intent|null{try{return JSON.parse(fs.readFileSync(target(stateRoot,blockId,lane),'utf8'))}catch{return null}}
function validateIntent(value:Intent,proofId:string,lane:PromotionLane,selector:string){if(value.schema!=='ecpe.profile-promotion-intent.v1'||value.proof_id!==proofId||value.lane!==lane||value.selector!==selector)throw new Error('promotion_intent_conflict')}
function applyProfilePromotionUnlocked(input:{stateRoot:string;cwd:string;proofId:string;lane:PromotionLane;assertSelector:string}){const expectedSelector=`/lanes/${input.lane}/activation`;if(input.assertSelector!==expectedSelector)throw new Error('promotion_selector_mismatch');const cwd=fs.realpathSync(path.resolve(input.cwd));const proof=inspectLanePromotionAssessment({stateRoot:input.stateRoot,blockId:findPromotionBlock(input.stateRoot,input.proofId,input.lane),participant:'portfolioops',lane:input.lane});if(!proof.eligible||proof.proof_id!==input.proofId)throw new Error('promotion_proof_invalid');const file=path.join(cwd,'.gstack','work-profile.yaml');const current=fs.readFileSync(file);const currentHash=digest(current);const existing=loadIntent(input.stateRoot,proof.block_id,input.lane);if(existing){validateIntent(existing,input.proofId,input.lane,expectedSelector);if(existing.phase==='written'){if(currentHash!==existing.after_sha256)throw new Error('promotion_profile_moved');return{result:'reused',phase:'written',record_id:existing.record_id,proof_id:existing.proof_id,lane:existing.lane}}if(currentHash===existing.after_sha256){existing.phase='written';existing.record_id=`promotion-write-${digest(JSON.stringify(existing)).slice(0,32)}`;write(target(input.stateRoot,proof.block_id,input.lane),existing);return{result:'reconciled',phase:'written',record_id:existing.record_id,proof_id:existing.proof_id,lane:existing.lane}}if(currentHash!==existing.before_sha256)throw new Error('promotion_profile_moved')}
  if(git(cwd,['status','--porcelain=v1','--untracked-files=all'],'promotion_git_invalid')!=='')throw new Error('promotion_dirty_input');const head=git(cwd,['rev-parse','HEAD^{commit}'],'promotion_git_invalid'),tree=git(cwd,['rev-parse','HEAD^{tree}'],'promotion_git_invalid');if(head!==proof.subject_head||tree!==proof.subject_tree)throw new Error('promotion_subject_moved');const beforeText=current.toString('utf8'),beforeProfile=parseWorkProfile(beforeText);if(beforeProfile.semantic_policy_hash!==proof.profile_hash||beforeProfile.lanes[input.lane].activation!=='shadow')throw new Error('promotion_profile_moved');const afterText=promotedBytes(beforeText,input.lane),after=Buffer.from(afterText),afterProfile=parseWorkProfile(afterText);const intent:Intent={schema:'ecpe.profile-promotion-intent.v1',phase:'prepared',proof_id:input.proofId,block_id:proof.block_id,participant:'portfolioops',lane:input.lane,selector:expectedSelector,subject_head:head,subject_tree:tree,before_sha256:currentHash,after_sha256:digest(after),before_profile_hash:beforeProfile.semantic_policy_hash,after_profile_hash:afterProfile.semantic_policy_hash,record_id:null};const intentTarget=target(input.stateRoot,proof.block_id,input.lane);write(intentTarget,intent);durableAtomicWrite(file,after,{mode:fs.statSync(file).mode&0o777,lockTarget:`${intentTarget}.profile-write`});intent.phase='written';intent.record_id=`promotion-write-${digest(JSON.stringify(intent)).slice(0,32)}`;write(intentTarget,intent);return{result:'written',phase:'written',record_id:intent.record_id,proof_id:intent.proof_id,lane:intent.lane,before_profile_hash:intent.before_profile_hash,after_profile_hash:intent.after_profile_hash}}
export function applyProfilePromotion(input:{stateRoot:string;cwd:string;proofId:string;lane:PromotionLane;assertSelector:string}){return withPromotionLock(input.stateRoot,input.proofId,input.lane,()=>applyProfilePromotionUnlocked(input))}
function findPromotionBlock(stateRoot:string,proofId:string,lane:PromotionLane):string{const directory=path.join(path.resolve(stateRoot),'ecpe','lane-promotions');let matches:string[]=[];try{matches=fs.readdirSync(directory).filter(name=>name.endsWith(`-${lane}.json`)).filter(name=>{try{return JSON.parse(fs.readFileSync(path.join(directory,name),'utf8')).assessment?.proof_id===proofId}catch{return false}})}catch{}if(matches.length!==1)throw new Error(matches.length?'promotion_proof_ambiguous':'promotion_proof_missing');return matches[0].slice(0,-(`-${lane}.json`.length))}
export function inspectProfilePromotion(input:{stateRoot:string;blockId:string;lane:PromotionLane}){const value=loadIntent(input.stateRoot,input.blockId,input.lane);if(!value)return{result:'absent',phase:'eligible',next_operation:'apply_profile_promotion'};return{result:value.phase==='written'?'written':'intent_recovery_required',phase:value.phase==='written'?'written':'intent_recovery_required',proof_id:value.proof_id,record_id:value.record_id,lane:value.lane,next_operation:value.phase==='written'?'ship':'lane_promotion_reconcile'}}
export function reconcileProfilePromotion(input:{stateRoot:string;cwd:string;blockId:string;lane:PromotionLane}){const intent=loadIntent(input.stateRoot,input.blockId,input.lane);if(!intent)throw new Error('promotion_intent_missing');const file=path.join(fs.realpathSync(path.resolve(input.cwd)),'.gstack','work-profile.yaml');const current=digest(fs.readFileSync(file));if(intent.phase==='written'){if(current!==intent.after_sha256)throw new Error('promotion_profile_moved');return{result:'reused',phase:'written',proof_id:intent.proof_id,record_id:intent.record_id,lane:intent.lane,next_operation:'ship'}}if(current===intent.before_sha256)return{result:'grant_required',phase:'prepared',proof_id:intent.proof_id,record_id:null,lane:intent.lane,next_operation:'apply_profile_promotion'};if(current!==intent.after_sha256)throw new Error('promotion_profile_moved');intent.phase='written';intent.record_id=`promotion-write-${digest(JSON.stringify(intent)).slice(0,32)}`;write(target(input.stateRoot,input.blockId,input.lane),intent);return{result:'reconciled',phase:'written',proof_id:intent.proof_id,record_id:intent.record_id,lane:intent.lane,next_operation:'ship'}}

export function inspectAuthorizedProfilePromotion(input:{stateRoot:string;cwd:string;lane:PromotionLane;trustedProfileHash:string;candidateProfileHash:string}):ProfilePromotionLineage|null{
  const directory=path.join(path.resolve(input.stateRoot),'ecpe','profile-promotion-intents');
  let names:string[]=[];
  try{names=fs.readdirSync(directory).filter(name=>name.endsWith(`-${input.lane}.json`))}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')return null;throw new Error('promotion_intent_invalid')}
  const matches=names.map(name=>{try{return JSON.parse(fs.readFileSync(path.join(directory,name),'utf8'))as Intent}catch{throw new Error('promotion_intent_invalid')}}).filter(intent=>intent.schema==='ecpe.profile-promotion-intent.v1'&&intent.phase==='written'&&intent.lane===input.lane&&intent.before_profile_hash===input.trustedProfileHash&&intent.after_profile_hash===input.candidateProfileHash);
  if(matches.length>1)throw new Error('promotion_intent_ambiguous');
  if(!matches.length)return null;
  const intent=matches[0];
  if(!intent.record_id||!/^promotion-write-[0-9a-f]{32}$/.test(intent.record_id))throw new Error('promotion_intent_invalid');
  const cwd=fs.realpathSync(path.resolve(input.cwd));
  const current=fs.readFileSync(path.join(cwd,'.gstack','work-profile.yaml'));
  if(digest(current)!==intent.after_sha256)throw new Error('promotion_profile_moved');
  const beforeChild=spawnSync('/usr/bin/git',['show',`${intent.subject_head}:.gstack/work-profile.yaml`],{cwd,encoding:'buffer',shell:false,env:{PATH:'/usr/bin:/bin',HOME:os.homedir(),LC_ALL:'C',GIT_CONFIG_NOSYSTEM:'1'}});if(beforeChild.status!==0)throw new Error('promotion_subject_moved');const before=beforeChild.stdout;
  const sourceTree=git(cwd,['rev-parse',`${intent.subject_head}^{tree}`],'promotion_subject_moved');
  if(digest(before)!==intent.before_sha256||sourceTree!==intent.subject_tree)throw new Error('promotion_subject_moved');
  const proof=inspectLanePromotionAssessment({stateRoot:input.stateRoot,blockId:intent.block_id,participant:'portfolioops',lane:input.lane});
  if(!proof.eligible||proof.proof_id!==intent.proof_id||proof.profile_hash!==intent.before_profile_hash||proof.subject_head!==intent.subject_head||proof.subject_tree!==intent.subject_tree)throw new Error('promotion_proof_invalid');
  return{block_id:intent.block_id,lane:intent.lane,proof_id:intent.proof_id,record_id:intent.record_id,before_profile_hash:intent.before_profile_hash,after_profile_hash:intent.after_profile_hash,before_sha256:intent.before_sha256,after_sha256:intent.after_sha256,subject_head:intent.subject_head,subject_tree:intent.subject_tree};
}
