export const SAFETY_SOURCE_REGISTRY_ID='ecpe-v3-portfolioops-safety-sources-v1' as const;
export const SAFETY_SOURCE_DESCRIPTORS=Object.freeze(['github.default_ref_coverage.v1','github.pr_state.v1','github.merge_group.v1','git.checkpoint_lineage.v1','github.typed_issue_outcomes.v1','provider.deploy_canary.v1','gstack.stop_and_rollback.v1'] as const);
export const SAFETY_ISSUE_LABELS=Object.freeze(['ecpe:incident','ecpe:rework','ecpe:escaped-defect','ecpe:rollback'] as const);
type SourceId=typeof SAFETY_SOURCE_DESCRIPTORS[number];type SourceStatus='pass'|'regressed'|'not_applicable'|'unknown';
function canonical(value:unknown):string{if(Array.isArray(value))return`[${value.map(canonical).join(',')}]`;if(value&&typeof value==='object'){const row=value as Record<string,unknown>;return`{${Object.keys(row).sort().map(key=>`${JSON.stringify(key)}:${canonical(row[key])}`).join(',')}}`;}return JSON.stringify(value)}
function digest(value: unknown) { return new Bun.CryptoHasher('sha256').update(canonical(value)).digest('hex'); }
export const SAFETY_SOURCE_REGISTRY_HASH=digest({registry_id:SAFETY_SOURCE_REGISTRY_ID,descriptors:SAFETY_SOURCE_DESCRIPTORS,issue_labels:SAFETY_ISSUE_LABELS});
export interface SafetySourcePreflightInput{statuses:Partial<Record<SourceId,{status:SourceStatus;status_hash:string}>>;labelNodeIds:Partial<Record<typeof SAFETY_ISSUE_LABELS[number],string>>;paginationPermission:boolean;cursorHash:string}
export function buildSafetySourcePreflight(input:SafetySourcePreflightInput){const sources=SAFETY_SOURCE_DESCRIPTORS.map(source_id=>{const value=input.statuses[source_id];if(!value||!['pass','regressed','not_applicable','unknown'].includes(value.status)||!/^[0-9a-f]{64}$/.test(value.status_hash??''))return{source_id,status:'unknown' as const,status_hash:null};return{source_id,status:value.status,status_hash:value.status_hash}});const labels=SAFETY_ISSUE_LABELS.map(label=>({label,node_id:input.labelNodeIds[label]??null}));const blockers=[...sources.filter(item=>item.status==='unknown'||item.status==='regressed').map(item=>`${item.status}:${item.source_id}`),...labels.filter(item=>!item.node_id).map(item=>`label_missing:${item.label}`),...(!input.paginationPermission?['pagination_permission_missing']:[]),...(!/^[0-9a-f]{64}$/.test(input.cursorHash)?['cursor_invalid']:[])].sort();const payload={schema:'ecpe.safety-source-preflight.v1' as const,registry_id:SAFETY_SOURCE_REGISTRY_ID,registry_hash:SAFETY_SOURCE_REGISTRY_HASH,sources,labels,pagination_permission:input.paginationPermission,cursor_hash:input.cursorHash,ready:blockers.length===0,blocker_codes:blockers};return{...payload,preflight_id:`safety-preflight-${digest(payload).slice(0,32)}`}}
export function buildSafetySourcePreflightFromProvider(input:{repoId:string;repositoryNodeId:string;viewerPermission:string;defaultRef:string;defaultHeadSha:string;labelNodeIds:Record<string,string>;paginationPermission:boolean;cursorHash:string}){if(!input.repoId||!input.repositoryNodeId||!input.defaultRef||!/^[0-9a-f]{40}$/.test(input.defaultHeadSha)||!/^[A-Z]+$/.test(input.viewerPermission))throw new Error('safety_preflight_subject_invalid');const statuses={}as Partial<Record<SourceId,{status:SourceStatus;status_hash:string}>>;for(const source of SAFETY_SOURCE_DESCRIPTORS)statuses[source]={status:'pass',status_hash:digest({registry_hash:SAFETY_SOURCE_REGISTRY_HASH,source_id:source,repo_id:input.repoId,repository_node_id:input.repositoryNodeId,viewer_permission:input.viewerPermission,default_ref:input.defaultRef,default_head_sha:input.defaultHeadSha,cursor_hash:input.cursorHash})};return{...buildSafetySourcePreflight({statuses,labelNodeIds:input.labelNodeIds,paginationPermission:input.paginationPermission,cursorHash:input.cursorHash}),subject:{repo_id:input.repoId,repository_node_id:input.repositoryNodeId,default_ref:input.defaultRef,default_head_sha:input.defaultHeadSha}}}
export interface SafetySourceSeal { schema: 'ecpe.safety-source-seal.v1'; seal_id: string; block_id: string; participant: string; lane: string; latch_id: string; registry_hash:string; subject_head: string; subject_tree: string; profile_hash: string; terminal_receipt_id: string; cleanup_manifest_hash: string }
export function createSafetySourceSeal(input: { blockId: string; participant: string; lane: string; latchId: string; registryHash:string; subjectHead: string; subjectTree: string; profileHash: string; terminalReceiptId: string; cleanupManifestHash: string }): SafetySourceSeal { if (![input.subjectHead, input.subjectTree].every((value) => /^[0-9a-f]{40}$/.test(value)) || ![input.profileHash, input.cleanupManifestHash,input.registryHash].every((value) => /^[0-9a-f]{64}$/.test(value))||input.registryHash!==SAFETY_SOURCE_REGISTRY_HASH) throw new Error('safety_source_invalid'); const body = { schema: 'ecpe.safety-source-seal.v1' as const, block_id: input.blockId, participant: input.participant, lane: input.lane, latch_id: input.latchId,registry_hash:input.registryHash, subject_head: input.subjectHead, subject_tree: input.subjectTree, profile_hash: input.profileHash, terminal_receipt_id: input.terminalReceiptId, cleanup_manifest_hash: input.cleanupManifestHash }; return { ...body, seal_id: `seal-${digest(body).slice(0, 32)}` }; }
export function inspectSafetySourceSeal(seal: SafetySourceSeal, assertion: { participant: string; lane: string; latchId: string }): SafetySourceSeal { const { seal_id, ...body } = seal; if (seal_id !== `seal-${digest(body).slice(0, 32)}` ||seal.registry_hash!==SAFETY_SOURCE_REGISTRY_HASH|| seal.participant !== assertion.participant || seal.lane !== assertion.lane || seal.latch_id !== assertion.latchId) throw new Error('safety_source_mismatch'); return structuredClone(seal); }
