import * as fs from 'node:fs';
import * as path from 'node:path';
import { buildChangeManifest } from '../../lib/change-manifest';
import { adapterRegistryHash } from '../../lib/deploy-adapter-registry';
import { resolveTrustedWorkProfile } from '../../lib/trusted-base';
import { compareCandidateProfile, LANES, parseWorkProfile, resolveProfileRequirements, type FinishLine, type Lane, type SemanticRole } from '../../lib/work-profile';

function fail(error: unknown): never { process.stderr.write(JSON.stringify({ result: null, error: { code: error instanceof Error ? error.message : 'work_profile_failed' } }) + '\n'); process.exit(2); }
function flags(args: string[]): Map<string, string[]> { const output = new Map<string, string[]>(); while (args.length) { const flag = args.shift()!; if (flag === '--json') { output.set(flag, ['true']); continue; } const value = args.shift(); if (!flag.startsWith('--') || !value || value.startsWith('--')) throw new Error('work_profile_arguments_invalid'); output.set(flag, [...(output.get(flag) ?? []), value]); } return output; }
function one(map: Map<string, string[]>, name: string): string | undefined { return map.get(name)?.at(-1); }
function allow(map: Map<string, string[]>, allowed: string[]): void { const set = new Set(allowed); for (const name of map.keys()) if (!set.has(name)) throw new Error('work_profile_arguments_invalid'); }
function lane(value?: string): Lane { const result = value ?? 'single_repo_code'; if (result === 'auto') return 'single_repo_code'; if (!LANES.includes(result as Lane)) throw new Error('lane_invalid'); return result as Lane; }

try {
  const args = process.argv.slice(2); const command = args.shift(); const values = flags(args); const asJson = values.has('--json');
  if (command === 'validate') { allow(values, ['--file', '--json']); const file = one(values, '--file'); if (!file || values.size !== (asJson ? 2 : 1)) throw new Error('work_profile_arguments_invalid'); const profile = parseWorkProfile(fs.readFileSync(path.resolve(file), 'utf8')); process.stdout.write(JSON.stringify({ schema: 'ecpe.work-profile-validation.v1', valid: true, profile_hash: profile.semantic_policy_hash, adapter_registry_hash: adapterRegistryHash() }) + '\n'); }
  else if (command === 'resolve') { allow(values, ['--lane', '--assert-target-ref', '--assert-target-sha', '--json']); const selected = lane(one(values, '--lane')); const result = resolveTrustedWorkProfile({ cwd: process.cwd(), lane: selected, assertTargetRef: one(values, '--assert-target-ref'), assertTargetSha: one(values, '--assert-target-sha') }); process.stdout.write(JSON.stringify(result) + '\n'); }
  else if (command === 'requirements') { allow(values, ['--lane', '--roles', '--finish-line', '--assert-target-ref', '--assert-target-sha', '--json']); const selected = lane(one(values, '--lane')); const resolved = resolveTrustedWorkProfile({ cwd: process.cwd(), lane: selected, assertTargetRef: one(values, '--assert-target-ref'), assertTargetSha: one(values, '--assert-target-sha') }); if (!resolved.effective) process.stdout.write(JSON.stringify({ mode: 'legacy', required_capabilities: [], validator_ids: [], covered_by: {}, validator_bindings: {}, unbound_capabilities: [] }) + '\n'); else { const roles = (one(values, '--roles') ?? '').split(',').filter(Boolean) as SemanticRole[]; const manifest = buildChangeManifest({ cwd: process.cwd(), profile: resolved.effective, targetBaseRef: resolved.trusted_base.target_ref ?? undefined, targetBaseSha: resolved.trusted_base.target_sha, mergeBaseSha: resolved.trusted_base.merge_base_sha }); const finish = (one(values, '--finish-line') ?? 'local_change') as FinishLine; process.stdout.write(JSON.stringify({ manifest_hash: manifest.manifest_hash, ...resolveProfileRequirements(resolved.effective, { roles: roles.length ? roles : manifest.roles, lane: selected, finishLine: finish }) }) + '\n'); } }
  else if (command === 'preview') { allow(values, ['--candidate-file', '--lane', '--repo', '--assert-target-ref', '--comparison-ref', '--json']); const file = one(values, '--candidate-file'); if (!file) throw new Error('candidate_file_required'); const selected = lane(one(values, '--lane')); const resolved = resolveTrustedWorkProfile({ cwd: one(values, '--repo') ?? process.cwd(), lane: selected, assertTargetRef: one(values, '--assert-target-ref'), advisoryComparisonRef: one(values, '--comparison-ref') }); const candidate = parseWorkProfile(fs.readFileSync(path.resolve(file), 'utf8')); const comparison = resolved.effective ? compareCandidateProfile(resolved.effective, candidate) : { state: 'ignored_untrusted', effective: null, warnings: ['first_profile_untrusted'] }; process.stdout.write(JSON.stringify({ schema: 'ecpe.work-profile-preview.v1', advisory_only: true, execution: 'legacy', trusted_base: resolved.trusted_base, candidate_state: comparison.state, warnings: [...resolved.warnings, ...comparison.warnings] }) + '\n'); }
  else if (command === 'preview-deploy-targets') { allow(values, ['--json']); const resolved = resolveTrustedWorkProfile({ cwd: process.cwd(), lane: 'single_repo_code' }); const targets = resolved.effective ? Object.values(resolved.effective.deploy_targets).map((target: any) => ({ id: target.id, trigger: target.trigger, environment_class: target.environment_class, binding: target.binding })) : []; process.stdout.write(JSON.stringify({ schema: 'ecpe.deploy-target-preview.v1', advisory_only: true, profile_write_count: 0, adapter_registry_hash: adapterRegistryHash(), targets }) + '\n'); }
  else throw new Error('work_profile_command_invalid');
} catch (error) { fail(error); }
