/**
 * Image provider implementations for gstack design.
 *
 * OpenAI uses the Responses API directly. Codex uses `codex exec` with the
 * image_generation tool, so signed-in ChatGPT subscription auth works without
 * exposing or copying OAuth tokens into gstack.
 */

import * as fs from "fs";
import { existsSync, readdirSync, statSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { ImageProvider, sanitizeProviderError } from "./auth";

export interface ImageGenerationCallResult {
  responseId: string;
  imageData?: string;
  outputPath?: string;
}

function ensurePng(pathname: string): boolean {
  if (!existsSync(pathname)) return false;
  const bytes = fs.readFileSync(pathname);
  return bytes.subarray(0, 8).toString("hex") === "89504e470d0a1a0a";
}

async function callOpenAIImageGeneration(
  apiKey: string,
  prompt: string,
  size: string,
  quality: string,
): Promise<ImageGenerationCallResult> {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 120_000);

  try {
    const response = await fetch("https://api.openai.com/v1/responses", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "gpt-4o",
        input: prompt,
        tools: [{
          type: "image_generation",
          size,
          quality,
        }],
      }),
      signal: controller.signal,
    });

    if (!response.ok) {
      const error = sanitizeProviderError(await response.text());
      if (response.status === 403 && error.includes("organization must be verified")) {
        throw new Error(
          "OpenAI organization verification required.\n"
          + "Go to https://platform.openai.com/settings/organization to verify.\n"
          + "After verification, wait up to 15 minutes for access to propagate.",
        );
      }
      throw new Error(`OpenAI API error (${response.status}): ${error.slice(0, 200)}`);
    }

    const data = await response.json() as any;
    const imageItem = data.output?.find((item: any) => item.type === "image_generation_call");

    if (!imageItem?.result) {
      throw new Error(
        `No image data in OpenAI response. Output types: ${data.output?.map((o: any) => o.type).join(", ") || "none"}`
      );
    }

    return {
      responseId: data.id,
      imageData: imageItem.result,
    };
  } finally {
    clearTimeout(timeout);
  }
}

function normalizeCodexSize(size: string): string {
  if (["1024x1024", "1536x1024", "1024x1536"].includes(size)) return size;
  if (size === "2048x1152" || size === "1792x1024") return "1536x1024";
  if (size === "1152x2048" || size === "1024x1792") return "1024x1536";
  return "1536x1024";
}

function buildCodexPrompt(prompt: string, outputPath: string, size: string, quality: string): string {
  return `Use your image_generation tool with model gpt-image-2 to generate this UI mockup.\n\nPrompt:\n${prompt}\n\nSize: ${normalizeCodexSize(size)}. Quality: ${quality}.\n\nSave or copy the resulting PNG exactly to this path: ${outputPath}.\n\nDo not create the PNG deterministically. You must use the image_generation tool. Do not use Python, ImageMagick, SVG, canvas, or any deterministic drawing fallback. The final artifact must be a real PNG generated by gpt-image-2. If Codex exposes the generated image only in the session log rather than as a filesystem file, stop after the image_generation call succeeds so the wrapper can persist that generated PNG.`;
}

function collectJsonlFiles(root: string, cutoffMs: number, files: string[] = []): string[] {
  if (!existsSync(root)) return files;
  for (const entry of readdirSync(root, { withFileTypes: true })) {
    const pathname = join(root, entry.name);
    if (entry.isDirectory()) {
      collectJsonlFiles(pathname, cutoffMs, files);
      continue;
    }
    if (!entry.isFile() || !entry.name.endsWith(".jsonl")) continue;
    if (statSync(pathname).mtimeMs >= cutoffMs) files.push(pathname);
  }
  return files;
}

async function writeLatestCodexImageFromSession(outputPath: string, startedAtMs: number): Promise<boolean> {
  const sessionsRoot = resolve(`${process.env.HOME}/.codex/sessions`);
  const files = collectJsonlFiles(sessionsRoot, startedAtMs - 60_000)
    .sort((a, b) => statSync(b).mtimeMs - statSync(a).mtimeMs);

  let latest: { timestamp: number; result: string } | undefined;
  for (const file of files) {
    const text = await readFile(file, "utf8");
    for (const line of text.split("\n")) {
      if (!line.includes('"image_generation_call"') || !line.includes('"result"')) continue;
      try {
        const event = JSON.parse(line);
        const result = event?.payload?.result;
        const timestamp = Date.parse(event?.timestamp ?? "");
        if (typeof result !== "string" || !result.startsWith("iVBOR")) continue;
        if (!Number.isFinite(timestamp) || timestamp < startedAtMs - 60_000) continue;
        if (!latest || timestamp > latest.timestamp) latest = { timestamp, result };
      } catch {
        continue;
      }
    }
  }
  if (!latest) return false;
  const bytes = Buffer.from(latest.result, "base64");
  if (bytes.subarray(0, 8).toString("hex") !== "89504e470d0a1a0a") return false;
  await writeFile(outputPath, bytes);
  return true;
}

async function callCodexImageGeneration(
  prompt: string,
  outputPath: string,
  size: string,
  quality: string,
): Promise<ImageGenerationCallResult> {
  await mkdir(dirname(outputPath), { recursive: true });
  const codexAgentModel = process.env.CODEX_AGENT_MODEL ?? "gpt-5.2";
  const startedAtMs = Date.now();
  const proc = Bun.spawn(
    [
      "codex",
      "exec",
      "--skip-git-repo-check",
      "--sandbox",
      "workspace-write",
      "--model",
      codexAgentModel,
      "--enable",
      "image_generation",
      buildCodexPrompt(prompt, outputPath, size, quality),
    ],
    { cwd: dirname(outputPath), stdout: "pipe", stderr: "pipe" }
  );
  const timeoutMs = 300_000;
  let timedOut = false;
  const timer = setTimeout(() => {
    timedOut = true;
    proc.kill("SIGTERM");
  }, timeoutMs);

  try {
    const exitCode = await proc.exited;
    const stdout = sanitizeProviderError(await new Response(proc.stdout).text());
    const stderr = sanitizeProviderError(await new Response(proc.stderr).text());
    if (!ensurePng(outputPath)) {
      await writeLatestCodexImageFromSession(outputPath, startedAtMs);
    }
    if (ensurePng(outputPath)) {
      return { responseId: `codex-${startedAtMs}`, outputPath };
    }
    const tail = `${stdout}\n${stderr}`.slice(-1500);
    if (timedOut) throw new Error(`codex backend timed out after ${timeoutMs}ms: ${tail}`);
    if (exitCode !== 0) throw new Error(`codex backend exited ${exitCode}: ${tail}`);
    throw new Error(`codex backend did not create output PNG at ${outputPath}. Last output: ${tail}`);
  } finally {
    clearTimeout(timer);
  }
}

export async function callImageGeneration(
  provider: ImageProvider,
  prompt: string,
  size: string,
  quality: string,
  outputPath?: string,
): Promise<ImageGenerationCallResult> {
  if (provider.kind === "openai") {
    return callOpenAIImageGeneration(provider.apiKey!, prompt, size, quality);
  }
  if (!outputPath) throw new Error("Codex image generation requires an output path");
  return callCodexImageGeneration(prompt, resolve(outputPath), size, quality);
}
